/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as InboxesRouteImport } from './routes/inboxes'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverSlugRouteImport } from './routes/discover_.$slug'
import { Route as ChannelsSlugRouteImport } from './routes/channels_.$slug'
import { Route as AuthSessionRouteImport } from './routes/auth.session'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SlugPublicRouteImport } from './routes/$slug.public'
import { Route as SlugManageRouteImport } from './routes/$slug.manage'
import { Route as ApiMasumiInboxAgentSyncRouteImport } from './routes/api.masumi.inbox-agent.sync'
import { Route as ApiMasumiInboxAgentRegisterRouteImport } from './routes/api.masumi.inbox-agent.register'
import { Route as ApiMasumiInboxAgentFindAgentsRouteImport } from './routes/api.masumi.inbox-agent.find-agents'
import { Route as ApiMasumiInboxAgentDeregisterRouteImport } from './routes/api.masumi.inbox-agent.deregister'
import { Route as ApiMasumiInboxAgentCreditsRouteImport } from './routes/api.masumi.inbox-agent.credits'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxesRoute = InboxesRouteImport.update({
  id: '/inboxes',
  path: '/inboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSlugRoute = DiscoverSlugRouteImport.update({
  id: '/discover_/$slug',
  path: '/discover/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsSlugRoute = ChannelsSlugRouteImport.update({
  id: '/channels_/$slug',
  path: '/channels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionRoute = AuthSessionRouteImport.update({
  id: '/auth/session',
  path: '/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPublicRoute = SlugPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => SlugRoute,
} as any)
const SlugManageRoute = SlugManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => SlugRoute,
} as any)
const ApiMasumiInboxAgentSyncRoute = ApiMasumiInboxAgentSyncRouteImport.update({
  id: '/api/masumi/inbox-agent/sync',
  path: '/api/masumi/inbox-agent/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasumiInboxAgentRegisterRoute =
  ApiMasumiInboxAgentRegisterRouteImport.update({
    id: '/api/masumi/inbox-agent/register',
    path: '/api/masumi/inbox-agent/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMasumiInboxAgentFindAgentsRoute =
  ApiMasumiInboxAgentFindAgentsRouteImport.update({
    id: '/api/masumi/inbox-agent/find-agents',
    path: '/api/masumi/inbox-agent/find-agents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMasumiInboxAgentDeregisterRoute =
  ApiMasumiInboxAgentDeregisterRouteImport.update({
    id: '/api/masumi/inbox-agent/deregister',
    path: '/api/masumi/inbox-agent/deregister',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMasumiInboxAgentCreditsRoute =
  ApiMasumiInboxAgentCreditsRouteImport.update({
    id: '/api/masumi/inbox-agent/credits',
    path: '/api/masumi/inbox-agent/credits',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/channels': typeof ChannelsRoute
  '/discover': typeof DiscoverRoute
  '/inboxes': typeof InboxesRoute
  '/security': typeof SecurityRoute
  '/$slug/manage': typeof SlugManageRoute
  '/$slug/public': typeof SlugPublicRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/session': typeof AuthSessionRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/api/masumi/inbox-agent/credits': typeof ApiMasumiInboxAgentCreditsRoute
  '/api/masumi/inbox-agent/deregister': typeof ApiMasumiInboxAgentDeregisterRoute
  '/api/masumi/inbox-agent/find-agents': typeof ApiMasumiInboxAgentFindAgentsRoute
  '/api/masumi/inbox-agent/register': typeof ApiMasumiInboxAgentRegisterRoute
  '/api/masumi/inbox-agent/sync': typeof ApiMasumiInboxAgentSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/channels': typeof ChannelsRoute
  '/discover': typeof DiscoverRoute
  '/inboxes': typeof InboxesRoute
  '/security': typeof SecurityRoute
  '/$slug/manage': typeof SlugManageRoute
  '/$slug/public': typeof SlugPublicRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/session': typeof AuthSessionRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/discover/$slug': typeof DiscoverSlugRoute
  '/api/masumi/inbox-agent/credits': typeof ApiMasumiInboxAgentCreditsRoute
  '/api/masumi/inbox-agent/deregister': typeof ApiMasumiInboxAgentDeregisterRoute
  '/api/masumi/inbox-agent/find-agents': typeof ApiMasumiInboxAgentFindAgentsRoute
  '/api/masumi/inbox-agent/register': typeof ApiMasumiInboxAgentRegisterRoute
  '/api/masumi/inbox-agent/sync': typeof ApiMasumiInboxAgentSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/channels': typeof ChannelsRoute
  '/discover': typeof DiscoverRoute
  '/inboxes': typeof InboxesRoute
  '/security': typeof SecurityRoute
  '/$slug/manage': typeof SlugManageRoute
  '/$slug/public': typeof SlugPublicRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/session': typeof AuthSessionRoute
  '/channels_/$slug': typeof ChannelsSlugRoute
  '/discover_/$slug': typeof DiscoverSlugRoute
  '/api/masumi/inbox-agent/credits': typeof ApiMasumiInboxAgentCreditsRoute
  '/api/masumi/inbox-agent/deregister': typeof ApiMasumiInboxAgentDeregisterRoute
  '/api/masumi/inbox-agent/find-agents': typeof ApiMasumiInboxAgentFindAgentsRoute
  '/api/masumi/inbox-agent/register': typeof ApiMasumiInboxAgentRegisterRoute
  '/api/masumi/inbox-agent/sync': typeof ApiMasumiInboxAgentSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/agents'
    | '/approvals'
    | '/channels'
    | '/discover'
    | '/inboxes'
    | '/security'
    | '/$slug/manage'
    | '/$slug/public'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/session'
    | '/channels/$slug'
    | '/discover/$slug'
    | '/api/masumi/inbox-agent/credits'
    | '/api/masumi/inbox-agent/deregister'
    | '/api/masumi/inbox-agent/find-agents'
    | '/api/masumi/inbox-agent/register'
    | '/api/masumi/inbox-agent/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/agents'
    | '/approvals'
    | '/channels'
    | '/discover'
    | '/inboxes'
    | '/security'
    | '/$slug/manage'
    | '/$slug/public'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/session'
    | '/channels/$slug'
    | '/discover/$slug'
    | '/api/masumi/inbox-agent/credits'
    | '/api/masumi/inbox-agent/deregister'
    | '/api/masumi/inbox-agent/find-agents'
    | '/api/masumi/inbox-agent/register'
    | '/api/masumi/inbox-agent/sync'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/agents'
    | '/approvals'
    | '/channels'
    | '/discover'
    | '/inboxes'
    | '/security'
    | '/$slug/manage'
    | '/$slug/public'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/session'
    | '/channels_/$slug'
    | '/discover_/$slug'
    | '/api/masumi/inbox-agent/credits'
    | '/api/masumi/inbox-agent/deregister'
    | '/api/masumi/inbox-agent/find-agents'
    | '/api/masumi/inbox-agent/register'
    | '/api/masumi/inbox-agent/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ChannelsRoute: typeof ChannelsRoute
  DiscoverRoute: typeof DiscoverRoute
  InboxesRoute: typeof InboxesRoute
  SecurityRoute: typeof SecurityRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSessionRoute: typeof AuthSessionRoute
  ChannelsSlugRoute: typeof ChannelsSlugRoute
  DiscoverSlugRoute: typeof DiscoverSlugRoute
  ApiMasumiInboxAgentCreditsRoute: typeof ApiMasumiInboxAgentCreditsRoute
  ApiMasumiInboxAgentDeregisterRoute: typeof ApiMasumiInboxAgentDeregisterRoute
  ApiMasumiInboxAgentFindAgentsRoute: typeof ApiMasumiInboxAgentFindAgentsRoute
  ApiMasumiInboxAgentRegisterRoute: typeof ApiMasumiInboxAgentRegisterRoute
  ApiMasumiInboxAgentSyncRoute: typeof ApiMasumiInboxAgentSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inboxes': {
      id: '/inboxes'
      path: '/inboxes'
      fullPath: '/inboxes'
      preLoaderRoute: typeof InboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover_/$slug': {
      id: '/discover_/$slug'
      path: '/discover/$slug'
      fullPath: '/discover/$slug'
      preLoaderRoute: typeof DiscoverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels_/$slug': {
      id: '/channels_/$slug'
      path: '/channels/$slug'
      fullPath: '/channels/$slug'
      preLoaderRoute: typeof ChannelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/session': {
      id: '/auth/session'
      path: '/auth/session'
      fullPath: '/auth/session'
      preLoaderRoute: typeof AuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/public': {
      id: '/$slug/public'
      path: '/public'
      fullPath: '/$slug/public'
      preLoaderRoute: typeof SlugPublicRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/manage': {
      id: '/$slug/manage'
      path: '/manage'
      fullPath: '/$slug/manage'
      preLoaderRoute: typeof SlugManageRouteImport
      parentRoute: typeof SlugRoute
    }
    '/api/masumi/inbox-agent/sync': {
      id: '/api/masumi/inbox-agent/sync'
      path: '/api/masumi/inbox-agent/sync'
      fullPath: '/api/masumi/inbox-agent/sync'
      preLoaderRoute: typeof ApiMasumiInboxAgentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masumi/inbox-agent/register': {
      id: '/api/masumi/inbox-agent/register'
      path: '/api/masumi/inbox-agent/register'
      fullPath: '/api/masumi/inbox-agent/register'
      preLoaderRoute: typeof ApiMasumiInboxAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masumi/inbox-agent/find-agents': {
      id: '/api/masumi/inbox-agent/find-agents'
      path: '/api/masumi/inbox-agent/find-agents'
      fullPath: '/api/masumi/inbox-agent/find-agents'
      preLoaderRoute: typeof ApiMasumiInboxAgentFindAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masumi/inbox-agent/deregister': {
      id: '/api/masumi/inbox-agent/deregister'
      path: '/api/masumi/inbox-agent/deregister'
      fullPath: '/api/masumi/inbox-agent/deregister'
      preLoaderRoute: typeof ApiMasumiInboxAgentDeregisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masumi/inbox-agent/credits': {
      id: '/api/masumi/inbox-agent/credits'
      path: '/api/masumi/inbox-agent/credits'
      fullPath: '/api/masumi/inbox-agent/credits'
      preLoaderRoute: typeof ApiMasumiInboxAgentCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SlugRouteChildren {
  SlugManageRoute: typeof SlugManageRoute
  SlugPublicRoute: typeof SlugPublicRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugManageRoute: SlugManageRoute,
  SlugPublicRoute: SlugPublicRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AgentsRoute: AgentsRoute,
  ApprovalsRoute: ApprovalsRoute,
  ChannelsRoute: ChannelsRoute,
  DiscoverRoute: DiscoverRoute,
  InboxesRoute: InboxesRoute,
  SecurityRoute: SecurityRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSessionRoute: AuthSessionRoute,
  ChannelsSlugRoute: ChannelsSlugRoute,
  DiscoverSlugRoute: DiscoverSlugRoute,
  ApiMasumiInboxAgentCreditsRoute: ApiMasumiInboxAgentCreditsRoute,
  ApiMasumiInboxAgentDeregisterRoute: ApiMasumiInboxAgentDeregisterRoute,
  ApiMasumiInboxAgentFindAgentsRoute: ApiMasumiInboxAgentFindAgentsRoute,
  ApiMasumiInboxAgentRegisterRoute: ApiMasumiInboxAgentRegisterRoute,
  ApiMasumiInboxAgentSyncRoute: ApiMasumiInboxAgentSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
