// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  requestId: __t.u64(),
  sourceDeviceId: __t.option(__t.string()),
  sourceEncryptionPublicKey: __t.string(),
  sourceEncryptionKeyVersion: __t.string(),
  sourceEncryptionAlgorithm: __t.option(__t.string()),
  bundleCiphertext: __t.string(),
  bundleIv: __t.string(),
  bundleAlgorithm: __t.string(),
  sharedAgentCount: __t.u64(),
  sharedKeyVersionCount: __t.u64(),
  expiresAt: __t.timestamp(),
};
