// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SecretEnvelopeAttachment,
} from "./types";

export default {
  agentDbId: __t.u64(),
  threadId: __t.u64(),
  membershipVersion: __t.u64(),
  secretVersion: __t.string(),
  get attachedSecretEnvelopes() {
    return __t.array(SecretEnvelopeAttachment);
  },
};
