// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  EncryptionAlgorithm,
  SigningAlgorithm,
} from "./types";

export default {
  slug: __t.string(),
  displayName: __t.option(__t.string()),
  encryptionPublicKey: __t.string(),
  keyBundleVersion: __t.u32(),
  get encryptionAlgorithm() {
    return EncryptionAlgorithm;
  },
  signingPublicKey: __t.string(),
  get signingAlgorithm() {
    return SigningAlgorithm;
  },
};
