// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  slug: __t.string(),
  displayName: __t.option(__t.string()),
  encryptionPublicKey: __t.string(),
  encryptionKeyVersion: __t.string(),
  encryptionAlgorithm: __t.option(__t.string()),
  signingPublicKey: __t.string(),
  signingKeyVersion: __t.string(),
  signingAlgorithm: __t.option(__t.string()),
};
