// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ThreadKind,
} from "./types";

export default {
  agentDbId: __t.u64(),
  get kind() {
    return ThreadKind;
  },
  otherAgentPublicIdentity: __t.option(__t.string()),
  participantPublicIdentities: __t.option(__t.array(__t.string())),
  title: __t.option(__t.string()),
};
