// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ChannelAccessMode,
  ChannelPermission,
} from "./types";

export default {
  agentDbId: __t.u64(),
  slug: __t.string(),
  title: __t.option(__t.string()),
  description: __t.option(__t.string()),
  get accessMode() {
    return ChannelAccessMode;
  },
  discoverable: __t.bool(),
  get defaultPermission() {
    return __t.option(ChannelPermission);
  },
};
