// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptThreadInviteReducer from "./accept_thread_invite_reducer";
import AddContactAllowlistEntryReducer from "./add_contact_allowlist_entry_reducer";
import AddThreadParticipantReducer from "./add_thread_participant_reducer";
import ApproveChannelJoinReducer from "./approve_channel_join_reducer";
import ApproveContactRequestReducer from "./approve_contact_request_reducer";
import ApproveDeviceShareRequestReducer from "./approve_device_share_request_reducer";
import CancelContactRequestReducer from "./cancel_contact_request_reducer";
import CreateAgentReducer from "./create_agent_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateDeviceShareRequestReducer from "./create_device_share_request_reducer";
import CreateThreadReducer from "./create_thread_reducer";
import DeclineThreadInviteReducer from "./decline_thread_invite_reducer";
import DeleteThreadReducer from "./delete_thread_reducer";
import JoinPublicChannelReducer from "./join_public_channel_reducer";
import RefreshAccountAuthLeaseReducer from "./refresh_account_auth_lease_reducer";
import RegisterDeviceReducer from "./register_device_reducer";
import RejectChannelJoinReducer from "./reject_channel_join_reducer";
import RejectContactRequestReducer from "./reject_contact_request_reducer";
import RemoveChannelMemberReducer from "./remove_channel_member_reducer";
import RemoveContactAllowlistEntryReducer from "./remove_contact_allowlist_entry_reducer";
import RemoveThreadParticipantReducer from "./remove_thread_participant_reducer";
import RequestChannelJoinReducer from "./request_channel_join_reducer";
import RequestDirectContactReducer from "./request_direct_contact_reducer";
import RevokeDeviceReducer from "./revoke_device_reducer";
import RotateAgentKeysReducer from "./rotate_agent_keys_reducer";
import SendChannelMessageReducer from "./send_channel_message_reducer";
import SendEncryptedMessageReducer from "./send_encrypted_message_reducer";
import SetThreadParticipantAdminReducer from "./set_thread_participant_admin_reducer";
import ShareDeviceKeyBundleReducer from "./share_device_key_bundle_reducer";
import UpdateAgentProfileReducer from "./update_agent_profile_reducer";
import UpdateChannelMemberPermissionReducer from "./update_channel_member_permission_reducer";
import UpdateChannelMemberReadStateReducer from "./update_channel_member_read_state_reducer";
import UpdateChannelSettingsReducer from "./update_channel_settings_reducer";
import UpdateThreadMessageRetentionReducer from "./update_thread_message_retention_reducer";
import UpdateThreadReadStateReducer from "./update_thread_read_state_reducer";
import UpsertAccountFromOidcIdentityReducer from "./upsert_account_from_oidc_identity_reducer";
import UpsertMasumiRegistrationReducer from "./upsert_masumi_registration_reducer";

// Import all procedure arg schemas
import * as ClaimDeviceKeyBundleProcedure from "./claim_device_key_bundle_procedure";
import * as ListChannelMembersProcedure from "./list_channel_members_procedure";
import * as ListChannelMessagesProcedure from "./list_channel_messages_procedure";
import * as ListContactAllowlistEntriesProcedure from "./list_contact_allowlist_entries_procedure";
import * as ListDiscoverableChannelsProcedure from "./list_discoverable_channels_procedure";
import * as ListOwnedAgentsPageProcedure from "./list_owned_agents_page_procedure";
import * as ListOwnedDevicesProcedure from "./list_owned_devices_procedure";
import * as ListPendingChannelJoinRequestsPageProcedure from "./list_pending_channel_join_requests_page_procedure";
import * as ListPendingContactRequestsPageProcedure from "./list_pending_contact_requests_page_procedure";
import * as ListPendingThreadInvitesPageProcedure from "./list_pending_thread_invites_page_procedure";
import * as ListPublicChannelMessagesProcedure from "./list_public_channel_messages_procedure";
import * as ListResolvedChannelJoinRequestsProcedure from "./list_resolved_channel_join_requests_procedure";
import * as ListResolvedContactRequestsProcedure from "./list_resolved_contact_requests_procedure";
import * as ListResolvedThreadInvitesProcedure from "./list_resolved_thread_invites_procedure";
import * as ListThreadMessagesProcedure from "./list_thread_messages_procedure";
import * as ListThreadParticipantsProcedure from "./list_thread_participants_procedure";
import * as ListThreadSecretEnvelopesProcedure from "./list_thread_secret_envelopes_procedure";
import * as ListVisibleChannelPageProcedure from "./list_visible_channel_page_procedure";
import * as ListVisibleThreadsProcedure from "./list_visible_threads_procedure";
import * as LookupAgentKeyBundlesProcedure from "./lookup_agent_key_bundles_procedure";
import * as LookupAgentPublicKeysProcedure from "./lookup_agent_public_keys_procedure";
import * as LookupPublicChannelBySlugProcedure from "./lookup_public_channel_by_slug_procedure";
import * as LookupPublishedAgentBySlugProcedure from "./lookup_published_agent_by_slug_procedure";
import * as LookupPublishedAgentSigningKeysProcedure from "./lookup_published_agent_signing_keys_procedure";
import * as LookupPublishedAgentsByEmailPageProcedure from "./lookup_published_agents_by_email_page_procedure";
import * as LookupPublishedPublicRouteBySlugProcedure from "./lookup_published_public_route_by_slug_procedure";
import * as ReadContactRequestProcedure from "./read_contact_request_procedure";
import * as ReadOwnedAgentProcedure from "./read_owned_agent_procedure";
import * as ReadVisibleChannelStateProcedure from "./read_visible_channel_state_procedure";
import * as ReadVisibleThreadProcedure from "./read_visible_thread_procedure";
import * as ResolveDeviceShareRequestByCodeProcedure from "./resolve_device_share_request_by_code_procedure";

// Import all table schema definitions
import VisibleAccountChangeSignalRow from "./visible_account_change_signal_table";
import VisibleAccountsRow from "./visible_accounts_table";
import VisibleChannelMembershipsRow from "./visible_channel_memberships_table";
import VisibleChannelsRow from "./visible_channels_table";
import VisibleDeviceKeyBundlesRow from "./visible_device_key_bundles_table";
import VisibleDeviceShareRequestsRow from "./visible_device_share_requests_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  visible_account_change_signal: __table({
    name: 'visible_account_change_signal',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAccountChangeSignalRow),
  visible_accounts: __table({
    name: 'visible_accounts',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAccountsRow),
  visible_channel_memberships: __table({
    name: 'visible_channel_memberships',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelMembershipsRow),
  visible_channels: __table({
    name: 'visible_channels',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelsRow),
  visible_device_key_bundles: __table({
    name: 'visible_device_key_bundles',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDeviceKeyBundlesRow),
  visible_device_share_requests: __table({
    name: 'visible_device_share_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDeviceShareRequestsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_thread_invite", AcceptThreadInviteReducer),
  __reducerSchema("add_contact_allowlist_entry", AddContactAllowlistEntryReducer),
  __reducerSchema("add_thread_participant", AddThreadParticipantReducer),
  __reducerSchema("approve_channel_join", ApproveChannelJoinReducer),
  __reducerSchema("approve_contact_request", ApproveContactRequestReducer),
  __reducerSchema("approve_device_share_request", ApproveDeviceShareRequestReducer),
  __reducerSchema("cancel_contact_request", CancelContactRequestReducer),
  __reducerSchema("create_agent", CreateAgentReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_device_share_request", CreateDeviceShareRequestReducer),
  __reducerSchema("create_thread", CreateThreadReducer),
  __reducerSchema("decline_thread_invite", DeclineThreadInviteReducer),
  __reducerSchema("delete_thread", DeleteThreadReducer),
  __reducerSchema("join_public_channel", JoinPublicChannelReducer),
  __reducerSchema("refresh_account_auth_lease", RefreshAccountAuthLeaseReducer),
  __reducerSchema("register_device", RegisterDeviceReducer),
  __reducerSchema("reject_channel_join", RejectChannelJoinReducer),
  __reducerSchema("reject_contact_request", RejectContactRequestReducer),
  __reducerSchema("remove_channel_member", RemoveChannelMemberReducer),
  __reducerSchema("remove_contact_allowlist_entry", RemoveContactAllowlistEntryReducer),
  __reducerSchema("remove_thread_participant", RemoveThreadParticipantReducer),
  __reducerSchema("request_channel_join", RequestChannelJoinReducer),
  __reducerSchema("request_direct_contact", RequestDirectContactReducer),
  __reducerSchema("revoke_device", RevokeDeviceReducer),
  __reducerSchema("rotate_agent_keys", RotateAgentKeysReducer),
  __reducerSchema("send_channel_message", SendChannelMessageReducer),
  __reducerSchema("send_encrypted_message", SendEncryptedMessageReducer),
  __reducerSchema("set_thread_participant_admin", SetThreadParticipantAdminReducer),
  __reducerSchema("share_device_key_bundle", ShareDeviceKeyBundleReducer),
  __reducerSchema("update_agent_profile", UpdateAgentProfileReducer),
  __reducerSchema("update_channel_member_permission", UpdateChannelMemberPermissionReducer),
  __reducerSchema("update_channel_member_read_state", UpdateChannelMemberReadStateReducer),
  __reducerSchema("update_channel_settings", UpdateChannelSettingsReducer),
  __reducerSchema("update_thread_message_retention", UpdateThreadMessageRetentionReducer),
  __reducerSchema("update_thread_read_state", UpdateThreadReadStateReducer),
  __reducerSchema("upsert_account_from_oidc_identity", UpsertAccountFromOidcIdentityReducer),
  __reducerSchema("upsert_masumi_registration", UpsertMasumiRegistrationReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("claim_device_key_bundle", ClaimDeviceKeyBundleProcedure.params, ClaimDeviceKeyBundleProcedure.returnType),
  __procedureSchema("list_channel_members", ListChannelMembersProcedure.params, ListChannelMembersProcedure.returnType),
  __procedureSchema("list_channel_messages", ListChannelMessagesProcedure.params, ListChannelMessagesProcedure.returnType),
  __procedureSchema("list_contact_allowlist_entries", ListContactAllowlistEntriesProcedure.params, ListContactAllowlistEntriesProcedure.returnType),
  __procedureSchema("list_discoverable_channels", ListDiscoverableChannelsProcedure.params, ListDiscoverableChannelsProcedure.returnType),
  __procedureSchema("list_owned_agents_page", ListOwnedAgentsPageProcedure.params, ListOwnedAgentsPageProcedure.returnType),
  __procedureSchema("list_owned_devices", ListOwnedDevicesProcedure.params, ListOwnedDevicesProcedure.returnType),
  __procedureSchema("list_pending_channel_join_requests_page", ListPendingChannelJoinRequestsPageProcedure.params, ListPendingChannelJoinRequestsPageProcedure.returnType),
  __procedureSchema("list_pending_contact_requests_page", ListPendingContactRequestsPageProcedure.params, ListPendingContactRequestsPageProcedure.returnType),
  __procedureSchema("list_pending_thread_invites_page", ListPendingThreadInvitesPageProcedure.params, ListPendingThreadInvitesPageProcedure.returnType),
  __procedureSchema("list_public_channel_messages", ListPublicChannelMessagesProcedure.params, ListPublicChannelMessagesProcedure.returnType),
  __procedureSchema("list_resolved_channel_join_requests", ListResolvedChannelJoinRequestsProcedure.params, ListResolvedChannelJoinRequestsProcedure.returnType),
  __procedureSchema("list_resolved_contact_requests", ListResolvedContactRequestsProcedure.params, ListResolvedContactRequestsProcedure.returnType),
  __procedureSchema("list_resolved_thread_invites", ListResolvedThreadInvitesProcedure.params, ListResolvedThreadInvitesProcedure.returnType),
  __procedureSchema("list_thread_messages", ListThreadMessagesProcedure.params, ListThreadMessagesProcedure.returnType),
  __procedureSchema("list_thread_participants", ListThreadParticipantsProcedure.params, ListThreadParticipantsProcedure.returnType),
  __procedureSchema("list_thread_secret_envelopes", ListThreadSecretEnvelopesProcedure.params, ListThreadSecretEnvelopesProcedure.returnType),
  __procedureSchema("list_visible_channel_page", ListVisibleChannelPageProcedure.params, ListVisibleChannelPageProcedure.returnType),
  __procedureSchema("list_visible_threads", ListVisibleThreadsProcedure.params, ListVisibleThreadsProcedure.returnType),
  __procedureSchema("lookup_agent_key_bundles", LookupAgentKeyBundlesProcedure.params, LookupAgentKeyBundlesProcedure.returnType),
  __procedureSchema("lookup_agent_public_keys", LookupAgentPublicKeysProcedure.params, LookupAgentPublicKeysProcedure.returnType),
  __procedureSchema("lookup_public_channel_by_slug", LookupPublicChannelBySlugProcedure.params, LookupPublicChannelBySlugProcedure.returnType),
  __procedureSchema("lookup_published_agent_by_slug", LookupPublishedAgentBySlugProcedure.params, LookupPublishedAgentBySlugProcedure.returnType),
  __procedureSchema("lookup_published_agent_signing_keys", LookupPublishedAgentSigningKeysProcedure.params, LookupPublishedAgentSigningKeysProcedure.returnType),
  __procedureSchema("lookup_published_agents_by_email_page", LookupPublishedAgentsByEmailPageProcedure.params, LookupPublishedAgentsByEmailPageProcedure.returnType),
  __procedureSchema("lookup_published_public_route_by_slug", LookupPublishedPublicRouteBySlugProcedure.params, LookupPublishedPublicRouteBySlugProcedure.returnType),
  __procedureSchema("read_contact_request", ReadContactRequestProcedure.params, ReadContactRequestProcedure.returnType),
  __procedureSchema("read_owned_agent", ReadOwnedAgentProcedure.params, ReadOwnedAgentProcedure.returnType),
  __procedureSchema("read_visible_channel_state", ReadVisibleChannelStateProcedure.params, ReadVisibleChannelStateProcedure.returnType),
  __procedureSchema("read_visible_thread", ReadVisibleThreadProcedure.params, ReadVisibleThreadProcedure.returnType),
  __procedureSchema("resolve_device_share_request_by_code", ResolveDeviceShareRequestByCodeProcedure.params, ResolveDeviceShareRequestByCodeProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

