// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptThreadInviteReducer from "./accept_thread_invite_reducer";
import AddContactAllowlistEntryReducer from "./add_contact_allowlist_entry_reducer";
import AddThreadParticipantReducer from "./add_thread_participant_reducer";
import ApproveChannelJoinReducer from "./approve_channel_join_reducer";
import ApproveContactRequestReducer from "./approve_contact_request_reducer";
import ApproveDeviceShareReducer from "./approve_device_share_reducer";
import BackfillThreadSecretEnvelopesReducer from "./backfill_thread_secret_envelopes_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateDeviceShareRequestReducer from "./create_device_share_request_reducer";
import CreateDirectThreadReducer from "./create_direct_thread_reducer";
import CreateGroupThreadReducer from "./create_group_thread_reducer";
import CreateInboxIdentityReducer from "./create_inbox_identity_reducer";
import CreatePendingDirectContactRequestReducer from "./create_pending_direct_contact_request_reducer";
import DeleteThreadReducer from "./delete_thread_reducer";
import JoinPublicChannelReducer from "./join_public_channel_reducer";
import MarkThreadReadReducer from "./mark_thread_read_reducer";
import RefreshInboxAuthLeaseReducer from "./refresh_inbox_auth_lease_reducer";
import RegisterDeviceReducer from "./register_device_reducer";
import RejectChannelJoinReducer from "./reject_channel_join_reducer";
import RejectContactRequestReducer from "./reject_contact_request_reducer";
import RejectThreadInviteReducer from "./reject_thread_invite_reducer";
import RemoveChannelMemberReducer from "./remove_channel_member_reducer";
import RemoveContactAllowlistEntryReducer from "./remove_contact_allowlist_entry_reducer";
import RemoveThreadParticipantReducer from "./remove_thread_participant_reducer";
import RequestChannelJoinReducer from "./request_channel_join_reducer";
import RequestDirectContactWithFirstMessageReducer from "./request_direct_contact_with_first_message_reducer";
import RevokeDeviceReducer from "./revoke_device_reducer";
import RotateAgentKeysReducer from "./rotate_agent_keys_reducer";
import SendChannelMessageReducer from "./send_channel_message_reducer";
import SendEncryptedMessageReducer from "./send_encrypted_message_reducer";
import SetAgentPublicDescriptionReducer from "./set_agent_public_description_reducer";
import SetAgentPublicLinkedEmailVisibilityReducer from "./set_agent_public_linked_email_visibility_reducer";
import SetAgentPublicMessageCapabilitiesReducer from "./set_agent_public_message_capabilities_reducer";
import SetChannelMemberPermissionReducer from "./set_channel_member_permission_reducer";
import SetThreadArchivedReducer from "./set_thread_archived_reducer";
import SetThreadParticipantAdminReducer from "./set_thread_participant_admin_reducer";
import UpdateAgentProfileReducer from "./update_agent_profile_reducer";
import UpdateChannelSettingsReducer from "./update_channel_settings_reducer";
import UpsertInboxFromOidcIdentityReducer from "./upsert_inbox_from_oidc_identity_reducer";
import UpsertMasumiInboxAgentRegistrationReducer from "./upsert_masumi_inbox_agent_registration_reducer";

// Import all procedure arg schemas
import * as ClaimDeviceKeyBundleProcedure from "./claim_device_key_bundle_procedure";
import * as ListChannelMembersProcedure from "./list_channel_members_procedure";
import * as ListChannelMessagesProcedure from "./list_channel_messages_procedure";
import * as ListDiscoverableChannelsProcedure from "./list_discoverable_channels_procedure";
import * as ListThreadMessagesProcedure from "./list_thread_messages_procedure";
import * as ListThreadSecretEnvelopesProcedure from "./list_thread_secret_envelopes_procedure";
import * as ListVisibleThreadsProcedure from "./list_visible_threads_procedure";
import * as LookupAgentKeyBundlesProcedure from "./lookup_agent_key_bundles_procedure";
import * as LookupPublishedAgentBySlugProcedure from "./lookup_published_agent_by_slug_procedure";
import * as LookupPublishedAgentSigningKeysProcedure from "./lookup_published_agent_signing_keys_procedure";
import * as LookupPublishedAgentsByEmailProcedure from "./lookup_published_agents_by_email_procedure";
import * as LookupPublishedPublicRouteBySlugProcedure from "./lookup_published_public_route_by_slug_procedure";
import * as ReadVisibleMessageSnapshotProcedure from "./read_visible_message_snapshot_procedure";
import * as ReadVisibleThreadProcedure from "./read_visible_thread_procedure";
import * as ResolveDeviceShareRequestByCodeProcedure from "./resolve_device_share_request_by_code_procedure";

// Import all table schema definitions
import PublicChannelRow from "./public_channel_table";
import PublicRecentChannelMessageRow from "./public_recent_channel_message_table";
import VisibleAgentKeyBundlesRow from "./visible_agent_key_bundles_table";
import VisibleAgentsRow from "./visible_agents_table";
import VisibleChannelJoinRequestsRow from "./visible_channel_join_requests_table";
import VisibleChannelMembershipsRow from "./visible_channel_memberships_table";
import VisibleChannelMessagesRow from "./visible_channel_messages_table";
import VisibleChannelsRow from "./visible_channels_table";
import VisibleContactAllowlistEntriesRow from "./visible_contact_allowlist_entries_table";
import VisibleContactRequestsRow from "./visible_contact_requests_table";
import VisibleDeviceKeyBundlesRow from "./visible_device_key_bundles_table";
import VisibleDeviceShareRequestsRow from "./visible_device_share_requests_table";
import VisibleDevicesRow from "./visible_devices_table";
import VisibleInboxesRow from "./visible_inboxes_table";
import VisibleMessagesRow from "./visible_messages_table";
import VisibleThreadInvitesRow from "./visible_thread_invites_table";
import VisibleThreadParticipantsRow from "./visible_thread_participants_table";
import VisibleThreadReadStatesRow from "./visible_thread_read_states_table";
import VisibleThreadSecretEnvelopesRow from "./visible_thread_secret_envelopes_table";
import VisibleThreadsRow from "./visible_threads_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  publicChannel: __table({
    name: 'public_channel',
    indexes: [
      { accessor: 'channelId', name: 'public_channel_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'id', name: 'public_channel_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'slug', name: 'public_channel_slug_idx_btree', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'public_channel_channel_id_key', constraint: 'unique', columns: ['channelId'] },
      { name: 'public_channel_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'public_channel_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, PublicChannelRow),
  publicRecentChannelMessage: __table({
    name: 'public_recent_channel_message',
    indexes: [
      { accessor: 'public_recent_channel_message_channel_id', name: 'public_recent_channel_message_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'channelSeqKey', name: 'public_recent_channel_message_channel_seq_key_idx_btree', algorithm: 'btree', columns: [
        'channelSeqKey',
      ] },
      { accessor: 'id', name: 'public_recent_channel_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'public_recent_channel_message_channel_seq_key_key', constraint: 'unique', columns: ['channelSeqKey'] },
      { name: 'public_recent_channel_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PublicRecentChannelMessageRow),
  visibleAgentKeyBundles: __table({
    name: 'visible_agent_key_bundles',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentKeyBundlesRow),
  visibleAgents: __table({
    name: 'visible_agents',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentsRow),
  visibleChannelJoinRequests: __table({
    name: 'visible_channel_join_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelJoinRequestsRow),
  visibleChannelMemberships: __table({
    name: 'visible_channel_memberships',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelMembershipsRow),
  visibleChannelMessages: __table({
    name: 'visible_channel_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelMessagesRow),
  visibleChannels: __table({
    name: 'visible_channels',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelsRow),
  visibleContactAllowlistEntries: __table({
    name: 'visible_contact_allowlist_entries',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleContactAllowlistEntriesRow),
  visibleContactRequests: __table({
    name: 'visible_contact_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleContactRequestsRow),
  visibleDeviceKeyBundles: __table({
    name: 'visible_device_key_bundles',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDeviceKeyBundlesRow),
  visibleDeviceShareRequests: __table({
    name: 'visible_device_share_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDeviceShareRequestsRow),
  visibleDevices: __table({
    name: 'visible_devices',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDevicesRow),
  visibleInboxes: __table({
    name: 'visible_inboxes',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleInboxesRow),
  visibleMessages: __table({
    name: 'visible_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleMessagesRow),
  visibleThreadInvites: __table({
    name: 'visible_thread_invites',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleThreadInvitesRow),
  visibleThreadParticipants: __table({
    name: 'visible_thread_participants',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleThreadParticipantsRow),
  visibleThreadReadStates: __table({
    name: 'visible_thread_read_states',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleThreadReadStatesRow),
  visibleThreadSecretEnvelopes: __table({
    name: 'visible_thread_secret_envelopes',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleThreadSecretEnvelopesRow),
  visibleThreads: __table({
    name: 'visible_threads',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleThreadsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_thread_invite", AcceptThreadInviteReducer),
  __reducerSchema("add_contact_allowlist_entry", AddContactAllowlistEntryReducer),
  __reducerSchema("add_thread_participant", AddThreadParticipantReducer),
  __reducerSchema("approve_channel_join", ApproveChannelJoinReducer),
  __reducerSchema("approve_contact_request", ApproveContactRequestReducer),
  __reducerSchema("approve_device_share", ApproveDeviceShareReducer),
  __reducerSchema("backfill_thread_secret_envelopes", BackfillThreadSecretEnvelopesReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_device_share_request", CreateDeviceShareRequestReducer),
  __reducerSchema("create_direct_thread", CreateDirectThreadReducer),
  __reducerSchema("create_group_thread", CreateGroupThreadReducer),
  __reducerSchema("create_inbox_identity", CreateInboxIdentityReducer),
  __reducerSchema("create_pending_direct_contact_request", CreatePendingDirectContactRequestReducer),
  __reducerSchema("delete_thread", DeleteThreadReducer),
  __reducerSchema("join_public_channel", JoinPublicChannelReducer),
  __reducerSchema("mark_thread_read", MarkThreadReadReducer),
  __reducerSchema("refresh_inbox_auth_lease", RefreshInboxAuthLeaseReducer),
  __reducerSchema("register_device", RegisterDeviceReducer),
  __reducerSchema("reject_channel_join", RejectChannelJoinReducer),
  __reducerSchema("reject_contact_request", RejectContactRequestReducer),
  __reducerSchema("reject_thread_invite", RejectThreadInviteReducer),
  __reducerSchema("remove_channel_member", RemoveChannelMemberReducer),
  __reducerSchema("remove_contact_allowlist_entry", RemoveContactAllowlistEntryReducer),
  __reducerSchema("remove_thread_participant", RemoveThreadParticipantReducer),
  __reducerSchema("request_channel_join", RequestChannelJoinReducer),
  __reducerSchema("request_direct_contact_with_first_message", RequestDirectContactWithFirstMessageReducer),
  __reducerSchema("revoke_device", RevokeDeviceReducer),
  __reducerSchema("rotate_agent_keys", RotateAgentKeysReducer),
  __reducerSchema("send_channel_message", SendChannelMessageReducer),
  __reducerSchema("send_encrypted_message", SendEncryptedMessageReducer),
  __reducerSchema("set_agent_public_description", SetAgentPublicDescriptionReducer),
  __reducerSchema("set_agent_public_linked_email_visibility", SetAgentPublicLinkedEmailVisibilityReducer),
  __reducerSchema("set_agent_public_message_capabilities", SetAgentPublicMessageCapabilitiesReducer),
  __reducerSchema("set_channel_member_permission", SetChannelMemberPermissionReducer),
  __reducerSchema("set_thread_archived", SetThreadArchivedReducer),
  __reducerSchema("set_thread_participant_admin", SetThreadParticipantAdminReducer),
  __reducerSchema("update_agent_profile", UpdateAgentProfileReducer),
  __reducerSchema("update_channel_settings", UpdateChannelSettingsReducer),
  __reducerSchema("upsert_inbox_from_oidc_identity", UpsertInboxFromOidcIdentityReducer),
  __reducerSchema("upsert_masumi_inbox_agent_registration", UpsertMasumiInboxAgentRegistrationReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("claim_device_key_bundle", ClaimDeviceKeyBundleProcedure.params, ClaimDeviceKeyBundleProcedure.returnType),
  __procedureSchema("list_channel_members", ListChannelMembersProcedure.params, ListChannelMembersProcedure.returnType),
  __procedureSchema("list_channel_messages", ListChannelMessagesProcedure.params, ListChannelMessagesProcedure.returnType),
  __procedureSchema("list_discoverable_channels", ListDiscoverableChannelsProcedure.params, ListDiscoverableChannelsProcedure.returnType),
  __procedureSchema("list_thread_messages", ListThreadMessagesProcedure.params, ListThreadMessagesProcedure.returnType),
  __procedureSchema("list_thread_secret_envelopes", ListThreadSecretEnvelopesProcedure.params, ListThreadSecretEnvelopesProcedure.returnType),
  __procedureSchema("list_visible_threads", ListVisibleThreadsProcedure.params, ListVisibleThreadsProcedure.returnType),
  __procedureSchema("lookup_agent_key_bundles", LookupAgentKeyBundlesProcedure.params, LookupAgentKeyBundlesProcedure.returnType),
  __procedureSchema("lookup_published_agent_by_slug", LookupPublishedAgentBySlugProcedure.params, LookupPublishedAgentBySlugProcedure.returnType),
  __procedureSchema("lookup_published_agent_signing_keys", LookupPublishedAgentSigningKeysProcedure.params, LookupPublishedAgentSigningKeysProcedure.returnType),
  __procedureSchema("lookup_published_agents_by_email", LookupPublishedAgentsByEmailProcedure.params, LookupPublishedAgentsByEmailProcedure.returnType),
  __procedureSchema("lookup_published_public_route_by_slug", LookupPublishedPublicRouteBySlugProcedure.params, LookupPublishedPublicRouteBySlugProcedure.returnType),
  __procedureSchema("read_visible_message_snapshot", ReadVisibleMessageSnapshotProcedure.params, ReadVisibleMessageSnapshotProcedure.returnType),
  __procedureSchema("read_visible_thread", ReadVisibleThreadProcedure.params, ReadVisibleThreadProcedure.returnType),
  __procedureSchema("resolve_device_share_request_by_code", ResolveDeviceShareRequestByCodeProcedure.params, ResolveDeviceShareRequestByCodeProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

