// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  VisibleChannelRow,
} from "./types";

export const params = {
  agentDbId: __t.u64(),
  beforeLastMessageAtMicros: __t.option(__t.u64()),
  beforeChannelId: __t.option(__t.u64()),
  limit: __t.u64(),
};
export const returnType = __t.array(VisibleChannelRow)