// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  channelId: __t.u64().name("channel_id"),
  channelSeq: __t.u64().name("channel_seq"),
  channelSeqKey: __t.string().name("channel_seq_key"),
  senderAgentDbId: __t.u64().name("sender_agent_db_id"),
  senderPublicIdentity: __t.string().name("sender_public_identity"),
  senderSeq: __t.u64().name("sender_seq"),
  senderSigningKeyVersion: __t.string().name("sender_signing_key_version"),
  plaintext: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()).name("reply_to_message_id"),
  createdAt: __t.timestamp().name("created_at"),
  senderSigningPublicKey: __t.string().name("sender_signing_public_key"),
});
