// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  channelId: __t.u64().name("channel_id"),
  slug: __t.string(),
  title: __t.option(__t.string()),
  description: __t.option(__t.string()),
  accessMode: __t.string().name("access_mode"),
  discoverable: __t.bool(),
  lastMessageSeq: __t.u64().name("last_message_seq"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  lastMessageAt: __t.timestamp().name("last_message_at"),
  publicJoinPermission: __t.string().name("public_join_permission"),
  sortKey: __t.string().name("sort_key"),
});
