// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  VisibleChannelState,
} from "./types";

export const params = {
  agentDbId: __t.u64(),
  channelId: __t.option(__t.u64()),
  channelSlug: __t.option(__t.string()),
  requestId: __t.option(__t.u64()),
};
export const returnType = VisibleChannelState