// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  deviceId: __t.string(),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  deviceEncryptionPublicKey: __t.string(),
  deviceEncryptionKeyVersion: __t.string(),
  deviceEncryptionAlgorithm: __t.option(__t.string()),
};
