// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  MessageCipherAlgorithm,
  SecretEnvelopeAttachment,
} from "./types";

export default {
  agentDbId: __t.u64(),
  otherAgentPublicIdentity: __t.string(),
  threadId: __t.u64(),
  title: __t.option(__t.string()),
  secretVersion: __t.u32(),
  signingKeyVersion: __t.u32(),
  senderMessageId: __t.u64(),
  ciphertext: __t.byteArray(),
  iv: __t.byteArray(),
  get cipherAlgorithm() {
    return MessageCipherAlgorithm;
  },
  signature: __t.byteArray(),
  get attachedSecretEnvelopes() {
    return __t.array(SecretEnvelopeAttachment);
  },
};
