// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SecretEnvelopeAttachment,
} from "./types";

export default {
  agentDbId: __t.u64(),
  otherAgentPublicIdentity: __t.string(),
  threadId: __t.u64(),
  membershipLocked: __t.option(__t.bool()),
  title: __t.option(__t.string()),
  secretVersion: __t.string(),
  signingKeyVersion: __t.string(),
  senderSeq: __t.u64(),
  ciphertext: __t.string(),
  iv: __t.string(),
  cipherAlgorithm: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  get attachedSecretEnvelopes() {
    return __t.array(SecretEnvelopeAttachment);
  },
};
