// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  DeviceKeyBundleAttachment,
} from "./types";

export default {
  agentDbId: __t.u64(),
  encryptionPublicKey: __t.string(),
  encryptionKeyVersion: __t.string(),
  encryptionAlgorithm: __t.option(__t.string()),
  signingPublicKey: __t.string(),
  signingKeyVersion: __t.string(),
  signingAlgorithm: __t.option(__t.string()),
  deviceKeyBundles: __t.option(__t.array(DeviceKeyBundleAttachment)),
  revokeDeviceIds: __t.option(__t.array(__t.string())),
};
