// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  agentDbId: __t.u64(),
  channelId: __t.u64(),
  senderMessageId: __t.u64(),
  senderSigningKeyVersion: __t.u32(),
  plaintext: __t.string(),
  signature: __t.byteArray(),
  replyToMessageId: __t.option(__t.u64()),
};
