// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  DeviceEncryptionAlgorithm,
  DeviceBundleAlgorithm,
} from "./types";

export default {
  targetDeviceId: __t.string(),
  sourceEncryptionPublicKey: __t.string(),
  sourceEncryptionKeyVersion: __t.u32(),
  get sourceEncryptionAlgorithm() {
    return DeviceEncryptionAlgorithm;
  },
  bundleCiphertext: __t.byteArray(),
  bundleIv: __t.byteArray(),
  get bundleAlgorithm() {
    return DeviceBundleAlgorithm;
  },
  sharedAgentCount: __t.u64(),
  sharedKeyVersionCount: __t.u64(),
};
