// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  id: __t.u64(),
  inboxId: __t.u64(),
  normalizedEmail: __t.string(),
  slug: __t.string(),
  inboxIdentifier: __t.option(__t.string()),
  isDefault: __t.bool(),
  publicIdentity: __t.string(),
  displayName: __t.option(__t.string()),
  publicLinkedEmailEnabled: __t.bool(),
  publicDescription: __t.option(__t.string()),
  allowAllMessageContentTypes: __t.option(__t.bool()),
  allowAllMessageHeaders: __t.option(__t.bool()),
  supportedMessageContentTypes: __t.option(__t.array(__t.string())),
  supportedMessageHeaderNames: __t.option(__t.array(__t.string())),
  currentEncryptionPublicKey: __t.string(),
  currentEncryptionKeyVersion: __t.string(),
  currentEncryptionAlgorithm: __t.string(),
  currentSigningPublicKey: __t.string(),
  currentSigningKeyVersion: __t.string(),
  currentSigningAlgorithm: __t.string(),
  masumiRegistrationNetwork: __t.option(__t.string()),
  masumiInboxAgentId: __t.option(__t.string()),
  masumiAgentIdentifier: __t.option(__t.string()),
  masumiRegistrationState: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentKeyBundle = __t.object("AgentKeyBundle", {
  id: __t.u64(),
  agentDbId: __t.u64(),
  publicIdentity: __t.string(),
  uniqueKey: __t.string(),
  encryptionPublicKey: __t.string(),
  encryptionKeyVersion: __t.string(),
  encryptionAlgorithm: __t.string(),
  signingPublicKey: __t.string(),
  signingKeyVersion: __t.string(),
  signingAlgorithm: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentKeyBundle = __Infer<typeof AgentKeyBundle>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  slug: __t.string(),
  title: __t.option(__t.string()),
  description: __t.option(__t.string()),
  accessMode: __t.string(),
  discoverable: __t.bool(),
  creatorAgentDbId: __t.u64(),
  nextChannelSeq: __t.u64(),
  lastMessageSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
  publicJoinPermission: __t.string(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelJoinRequest = __t.object("ChannelJoinRequest", {
  id: __t.u64(),
  channelId: __t.u64(),
  requesterAgentDbId: __t.u64(),
  requesterInboxId: __t.u64(),
  uniqueKey: __t.string(),
  permission: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type ChannelJoinRequest = __Infer<typeof ChannelJoinRequest>;

export const ChannelMember = __t.object("ChannelMember", {
  id: __t.u64(),
  channelId: __t.u64(),
  agentDbId: __t.u64(),
  inboxId: __t.u64(),
  uniqueKey: __t.string(),
  permission: __t.string(),
  active: __t.bool(),
  lastSentSeq: __t.u64(),
  joinedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelMember = __Infer<typeof ChannelMember>;

export const ChannelMemberListRow = __t.object("ChannelMemberListRow", {
  id: __t.u64(),
  channelId: __t.u64(),
  agentDbId: __t.u64(),
  agentPublicIdentity: __t.string(),
  agentSlug: __t.string(),
  agentDisplayName: __t.option(__t.string()),
  agentCurrentEncryptionPublicKey: __t.string(),
  agentCurrentEncryptionKeyVersion: __t.string(),
  permission: __t.string(),
  active: __t.bool(),
  lastSentSeq: __t.u64(),
  joinedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelMemberListRow = __Infer<typeof ChannelMemberListRow>;

export const ChannelMessage = __t.object("ChannelMessage", {
  id: __t.u64(),
  channelId: __t.u64(),
  channelSeq: __t.u64(),
  channelSeqKey: __t.string(),
  senderAgentDbId: __t.u64(),
  senderPublicIdentity: __t.string(),
  senderSeq: __t.u64(),
  senderSigningKeyVersion: __t.string(),
  plaintext: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type ChannelMessage = __Infer<typeof ChannelMessage>;

export const ChannelMessageRow = __t.object("ChannelMessageRow", {
  id: __t.u64(),
  channelId: __t.u64(),
  channelSeq: __t.u64(),
  senderAgentDbId: __t.u64(),
  senderPublicIdentity: __t.string(),
  senderSeq: __t.u64(),
  senderSigningPublicKey: __t.string(),
  senderSigningKeyVersion: __t.string(),
  plaintext: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type ChannelMessageRow = __Infer<typeof ChannelMessageRow>;

export const ClaimedDeviceKeyBundleRow = __t.object("ClaimedDeviceKeyBundleRow", {
  bundleId: __t.u64(),
  targetDeviceId: __t.string(),
  sourceDeviceId: __t.option(__t.string()),
  sourceEncryptionPublicKey: __t.string(),
  sourceEncryptionKeyVersion: __t.string(),
  sourceEncryptionAlgorithm: __t.string(),
  bundleCiphertext: __t.string(),
  bundleIv: __t.string(),
  bundleAlgorithm: __t.string(),
  sharedAgentCount: __t.u64(),
  sharedKeyVersionCount: __t.u64(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  get expiryMode() {
    return DeviceKeyBundleExpiryMode;
  },
});
export type ClaimedDeviceKeyBundleRow = __Infer<typeof ClaimedDeviceKeyBundleRow>;

export const ContactAllowlistEntry = __t.object("ContactAllowlistEntry", {
  id: __t.u64(),
  inboxId: __t.u64(),
  get kind() {
    return ContactAllowlistKind;
  },
  uniqueKey: __t.string(),
  agentPublicIdentity: __t.option(__t.string()),
  agentSlug: __t.option(__t.string()),
  agentDisplayName: __t.option(__t.string()),
  normalizedEmail: __t.option(__t.string()),
  displayEmail: __t.option(__t.string()),
  createdByAgentDbId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type ContactAllowlistEntry = __Infer<typeof ContactAllowlistEntry>;

// The tagged union or sum type for the algebraic type `ContactAllowlistKind`.
export const ContactAllowlistKind = __t.enum("ContactAllowlistKind", {
  Agent: __t.unit(),
  Email: __t.unit(),
});
export type ContactAllowlistKind = __Infer<typeof ContactAllowlistKind>;

export const ContactRequest = __t.object("ContactRequest", {
  id: __t.u64(),
  threadId: __t.u64(),
  requesterAgentDbId: __t.u64(),
  requesterPublicIdentity: __t.string(),
  requesterSlug: __t.string(),
  requesterDisplayName: __t.option(__t.string()),
  requesterNormalizedEmail: __t.string(),
  requesterDisplayEmail: __t.string(),
  targetAgentDbId: __t.u64(),
  targetPublicIdentity: __t.string(),
  targetSlug: __t.string(),
  targetDisplayName: __t.option(__t.string()),
  get status() {
    return ContactRequestStatus;
  },
  hiddenMessageCount: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type ContactRequest = __Infer<typeof ContactRequest>;

// The tagged union or sum type for the algebraic type `ContactRequestStatus`.
export const ContactRequestStatus = __t.enum("ContactRequestStatus", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Rejected: __t.unit(),
});
export type ContactRequestStatus = __Infer<typeof ContactRequestStatus>;

export const Device = __t.object("Device", {
  id: __t.u64(),
  deviceId: __t.string(),
  inboxId: __t.u64(),
  uniqueKey: __t.string(),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  deviceEncryptionPublicKey: __t.string(),
  deviceEncryptionKeyVersion: __t.string(),
  deviceEncryptionAlgorithm: __t.string(),
  status: __t.string(),
  approvedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type Device = __Infer<typeof Device>;

export const DeviceKeyBundle = __t.object("DeviceKeyBundle", {
  id: __t.u64(),
  targetDeviceId: __t.string(),
  inboxId: __t.u64(),
  sourceDeviceId: __t.option(__t.string()),
  sourceEncryptionPublicKey: __t.string(),
  sourceEncryptionKeyVersion: __t.string(),
  sourceEncryptionAlgorithm: __t.string(),
  bundleCiphertext: __t.string(),
  bundleIv: __t.string(),
  bundleAlgorithm: __t.string(),
  sharedAgentCount: __t.u64(),
  sharedKeyVersionCount: __t.u64(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  consumedAt: __t.option(__t.timestamp()),
  get expiryMode() {
    return DeviceKeyBundleExpiryMode;
  },
});
export type DeviceKeyBundle = __Infer<typeof DeviceKeyBundle>;

export const DeviceKeyBundleAttachment = __t.object("DeviceKeyBundleAttachment", {
  deviceId: __t.string(),
  sourceDeviceId: __t.option(__t.string()),
  sourceEncryptionPublicKey: __t.string(),
  sourceEncryptionKeyVersion: __t.string(),
  sourceEncryptionAlgorithm: __t.option(__t.string()),
  bundleCiphertext: __t.string(),
  bundleIv: __t.string(),
  bundleAlgorithm: __t.string(),
  sharedAgentCount: __t.u64(),
  sharedKeyVersionCount: __t.u64(),
  expiresAt: __t.timestamp(),
  get expiryMode() {
    return DeviceKeyBundleExpiryMode;
  },
});
export type DeviceKeyBundleAttachment = __Infer<typeof DeviceKeyBundleAttachment>;

export const DeviceKeyBundleExpiry = __t.object("DeviceKeyBundleExpiry", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bundleId: __t.u64(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type DeviceKeyBundleExpiry = __Infer<typeof DeviceKeyBundleExpiry>;

// The tagged union or sum type for the algebraic type `DeviceKeyBundleExpiryMode`.
export const DeviceKeyBundleExpiryMode = __t.enum("DeviceKeyBundleExpiryMode", {
  Expires: __t.unit(),
  NeverExpires: __t.unit(),
});
export type DeviceKeyBundleExpiryMode = __Infer<typeof DeviceKeyBundleExpiryMode>;

export const DeviceShareRequest = __t.object("DeviceShareRequest", {
  id: __t.u64(),
  deviceId: __t.string(),
  inboxId: __t.u64(),
  verificationCodeHash: __t.string(),
  clientCreatedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  approvedAt: __t.option(__t.timestamp()),
  consumedAt: __t.option(__t.timestamp()),
});
export type DeviceShareRequest = __Infer<typeof DeviceShareRequest>;

export const DirectThreadIndex = __t.object("DirectThreadIndex", {
  id: __t.u64(),
  directKey: __t.string(),
  threadId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type DirectThreadIndex = __Infer<typeof DirectThreadIndex>;

export const Inbox = __t.object("Inbox", {
  id: __t.u64(),
  normalizedEmail: __t.string(),
  displayEmail: __t.string(),
  ownerIdentity: __t.identity(),
  authSubject: __t.string(),
  authIssuer: __t.string(),
  authIdentityKey: __t.string(),
  authVerified: __t.bool(),
  emailAttested: __t.bool(),
  authVerifiedAt: __t.timestamp(),
  authExpiresAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Inbox = __Infer<typeof Inbox>;

export const InboxAuthLease = __t.object("InboxAuthLease", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  inboxId: __t.u64(),
  authIdentityKey: __t.string(),
  normalizedEmail: __t.string(),
  authIssuer: __t.string(),
  authSubject: __t.string(),
  expiresAt: __t.timestamp(),
  active: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type InboxAuthLease = __Infer<typeof InboxAuthLease>;

export const InboxAuthLeaseExpiry = __t.object("InboxAuthLeaseExpiry", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  leaseId: __t.u64(),
  ownerIdentity: __t.identity(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type InboxAuthLeaseExpiry = __Infer<typeof InboxAuthLeaseExpiry>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  threadId: __t.u64(),
  threadSeq: __t.u64(),
  threadSeqKey: __t.string(),
  membershipVersion: __t.u64(),
  senderAgentDbId: __t.u64(),
  senderSeq: __t.u64(),
  secretVersion: __t.string(),
  secretVersionStart: __t.bool(),
  signingKeyVersion: __t.string(),
  ciphertext: __t.string(),
  iv: __t.string(),
  cipherAlgorithm: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const PublicChannel = __t.object("PublicChannel", {
  id: __t.u64(),
  channelId: __t.u64(),
  slug: __t.string(),
  title: __t.option(__t.string()),
  description: __t.option(__t.string()),
  accessMode: __t.string(),
  discoverable: __t.bool(),
  lastMessageSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
  publicJoinPermission: __t.string(),
});
export type PublicChannel = __Infer<typeof PublicChannel>;

export const PublicRecentChannelMessage = __t.object("PublicRecentChannelMessage", {
  id: __t.u64(),
  channelId: __t.u64(),
  channelSeq: __t.u64(),
  channelSeqKey: __t.string(),
  senderAgentDbId: __t.u64(),
  senderPublicIdentity: __t.string(),
  senderSeq: __t.u64(),
  senderSigningKeyVersion: __t.string(),
  plaintext: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type PublicRecentChannelMessage = __Infer<typeof PublicRecentChannelMessage>;

export const PublishedAgentLookupRow = __t.object("PublishedAgentLookupRow", {
  slug: __t.string(),
  publicIdentity: __t.string(),
  isDefault: __t.bool(),
  displayName: __t.option(__t.string()),
  agentIdentifier: __t.option(__t.string()),
  encryptionKeyVersion: __t.string(),
  encryptionAlgorithm: __t.string(),
  encryptionPublicKey: __t.string(),
  signingKeyVersion: __t.string(),
  signingAlgorithm: __t.string(),
  signingPublicKey: __t.string(),
});
export type PublishedAgentLookupRow = __Infer<typeof PublishedAgentLookupRow>;

export const PublishedContactPolicyRow = __t.object("PublishedContactPolicyRow", {
  mode: __t.string(),
  allowlistScope: __t.string(),
  allowlistKinds: __t.array(__t.string()),
  messagePreviewVisibleBeforeApproval: __t.bool(),
});
export type PublishedContactPolicyRow = __Infer<typeof PublishedContactPolicyRow>;

export const PublishedPublicHeaderCapabilityRow = __t.object("PublishedPublicHeaderCapabilityRow", {
  name: __t.string(),
  required: __t.option(__t.bool()),
  allowMultiple: __t.option(__t.bool()),
  sensitive: __t.option(__t.bool()),
  allowedPrefixes: __t.option(__t.array(__t.string())),
});
export type PublishedPublicHeaderCapabilityRow = __Infer<typeof PublishedPublicHeaderCapabilityRow>;

export const PublishedPublicRouteRow = __t.object("PublishedPublicRouteRow", {
  agentIdentifier: __t.option(__t.string()),
  linkedEmail: __t.option(__t.string()),
  description: __t.option(__t.string()),
  encryptionKeyVersion: __t.string(),
  encryptionAlgorithm: __t.string(),
  encryptionPublicKey: __t.string(),
  signingKeyVersion: __t.string(),
  signingAlgorithm: __t.string(),
  signingPublicKey: __t.string(),
  allowAllContentTypes: __t.bool(),
  allowAllHeaders: __t.bool(),
  supportedContentTypes: __t.array(__t.string()),
  get supportedHeaders() {
    return __t.array(PublishedPublicHeaderCapabilityRow);
  },
  get contactPolicy() {
    return PublishedContactPolicyRow;
  },
});
export type PublishedPublicRouteRow = __Infer<typeof PublishedPublicRouteRow>;

export const RateLimit = __t.object("RateLimit", {
  id: __t.u64(),
  bucketKey: __t.string(),
  action: __t.string(),
  ownerIdentity: __t.identity(),
  windowStart: __t.timestamp(),
  expiresAt: __t.timestamp(),
  count: __t.u64(),
  limitedCount: __t.u64(),
  firstLimitedAt: __t.option(__t.timestamp()),
  lastLimitedAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type RateLimit = __Infer<typeof RateLimit>;

export const RateLimitCleanup = __t.object("RateLimitCleanup", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bucketKey: __t.string(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type RateLimitCleanup = __Infer<typeof RateLimitCleanup>;

export const RateLimitReport = __t.object("RateLimitReport", {
  id: __t.u64(),
  reportKey: __t.string(),
  bucketKey: __t.string(),
  action: __t.string(),
  ownerIdentity: __t.identity(),
  windowStart: __t.timestamp(),
  windowExpiresAt: __t.timestamp(),
  allowedCount: __t.u64(),
  limitedCount: __t.u64(),
  firstLimitedAt: __t.option(__t.timestamp()),
  lastLimitedAt: __t.option(__t.timestamp()),
  reportedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type RateLimitReport = __Infer<typeof RateLimitReport>;

export const RateLimitReportCleanup = __t.object("RateLimitReportCleanup", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  reportId: __t.u64(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type RateLimitReportCleanup = __Infer<typeof RateLimitReportCleanup>;

export const ResolvedDeviceShareRequestRow = __t.object("ResolvedDeviceShareRequestRow", {
  requestId: __t.u64(),
  deviceId: __t.string(),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  deviceEncryptionPublicKey: __t.string(),
  deviceEncryptionKeyVersion: __t.string(),
  deviceEncryptionAlgorithm: __t.string(),
  clientCreatedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type ResolvedDeviceShareRequestRow = __Infer<typeof ResolvedDeviceShareRequestRow>;

export const SecretEnvelopeAttachment = __t.object("SecretEnvelopeAttachment", {
  recipientPublicIdentity: __t.string(),
  recipientEncryptionKeyVersion: __t.string(),
  senderEncryptionKeyVersion: __t.string(),
  signingKeyVersion: __t.string(),
  wrappedSecretCiphertext: __t.string(),
  wrappedSecretIv: __t.string(),
  wrapAlgorithm: __t.string(),
  signature: __t.string(),
});
export type SecretEnvelopeAttachment = __Infer<typeof SecretEnvelopeAttachment>;

export const SelectedPublicRecentChannelMessageRow = __t.object("SelectedPublicRecentChannelMessageRow", {
  id: __t.u64(),
  channelId: __t.u64(),
  channelSeq: __t.u64(),
  senderAgentDbId: __t.u64(),
  senderPublicIdentity: __t.string(),
  senderSeq: __t.u64(),
  senderSigningPublicKey: __t.string(),
  senderSigningKeyVersion: __t.string(),
  plaintext: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type SelectedPublicRecentChannelMessageRow = __Infer<typeof SelectedPublicRecentChannelMessageRow>;

export const SelectedPublicRecentChannelMessages = __t.object("SelectedPublicRecentChannelMessages", {});
export type SelectedPublicRecentChannelMessages = __Infer<typeof SelectedPublicRecentChannelMessages>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  dedupeKey: __t.string(),
  kind: __t.string(),
  membershipLocked: __t.bool(),
  title: __t.option(__t.string()),
  creatorAgentDbId: __t.u64(),
  membershipVersion: __t.u64(),
  nextThreadSeq: __t.u64(),
  lastMessageSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
});
export type Thread = __Infer<typeof Thread>;

export const ThreadInvite = __t.object("ThreadInvite", {
  id: __t.u64(),
  threadId: __t.u64(),
  inviterAgentDbId: __t.u64(),
  inviteeAgentDbId: __t.u64(),
  inviteeInboxId: __t.u64(),
  uniqueKey: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type ThreadInvite = __Infer<typeof ThreadInvite>;

export const ThreadParticipant = __t.object("ThreadParticipant", {
  id: __t.u64(),
  threadId: __t.u64(),
  agentDbId: __t.u64(),
  inboxId: __t.u64(),
  uniqueKey: __t.string(),
  joinedAt: __t.timestamp(),
  lastSentSeq: __t.u64(),
  lastSentMembershipVersion: __t.option(__t.u64()),
  lastSentSecretVersion: __t.option(__t.string()),
  isAdmin: __t.bool(),
  active: __t.bool(),
});
export type ThreadParticipant = __Infer<typeof ThreadParticipant>;

export const ThreadReadState = __t.object("ThreadReadState", {
  id: __t.u64(),
  threadId: __t.u64(),
  agentDbId: __t.u64(),
  uniqueKey: __t.string(),
  lastReadThreadSeq: __t.option(__t.u64()),
  archived: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type ThreadReadState = __Infer<typeof ThreadReadState>;

export const ThreadSecretEnvelope = __t.object("ThreadSecretEnvelope", {
  id: __t.u64(),
  threadId: __t.u64(),
  membershipVersion: __t.u64(),
  secretVersion: __t.string(),
  senderAgentDbId: __t.u64(),
  recipientAgentDbId: __t.u64(),
  uniqueKey: __t.string(),
  senderEncryptionKeyVersion: __t.string(),
  recipientEncryptionKeyVersion: __t.string(),
  signingKeyVersion: __t.string(),
  wrappedSecretCiphertext: __t.string(),
  wrappedSecretIv: __t.string(),
  wrapAlgorithm: __t.string(),
  signature: __t.string(),
  createdAt: __t.timestamp(),
});
export type ThreadSecretEnvelope = __Infer<typeof ThreadSecretEnvelope>;

export const VisibleAgentKeyBundleRow = __t.object("VisibleAgentKeyBundleRow", {
  id: __t.u64(),
  agentDbId: __t.u64(),
  publicIdentity: __t.string(),
  encryptionPublicKey: __t.string(),
  encryptionKeyVersion: __t.string(),
  encryptionAlgorithm: __t.string(),
  signingPublicKey: __t.string(),
  signingKeyVersion: __t.string(),
  signingAlgorithm: __t.string(),
  createdAt: __t.timestamp(),
});
export type VisibleAgentKeyBundleRow = __Infer<typeof VisibleAgentKeyBundleRow>;

export const VisibleAgentKeyBundles = __t.object("VisibleAgentKeyBundles", {});
export type VisibleAgentKeyBundles = __Infer<typeof VisibleAgentKeyBundles>;

export const VisibleAgentRow = __t.object("VisibleAgentRow", {
  id: __t.u64(),
  inboxId: __t.u64(),
  normalizedEmail: __t.string(),
  slug: __t.string(),
  inboxIdentifier: __t.option(__t.string()),
  isDefault: __t.bool(),
  publicIdentity: __t.string(),
  displayName: __t.option(__t.string()),
  publicLinkedEmailEnabled: __t.bool(),
  publicDescription: __t.option(__t.string()),
  allowAllMessageContentTypes: __t.option(__t.bool()),
  allowAllMessageHeaders: __t.option(__t.bool()),
  supportedMessageContentTypes: __t.option(__t.array(__t.string())),
  supportedMessageHeaderNames: __t.option(__t.array(__t.string())),
  currentEncryptionPublicKey: __t.string(),
  currentEncryptionKeyVersion: __t.string(),
  currentEncryptionAlgorithm: __t.string(),
  currentSigningPublicKey: __t.string(),
  currentSigningKeyVersion: __t.string(),
  currentSigningAlgorithm: __t.string(),
  masumiRegistrationNetwork: __t.option(__t.string()),
  masumiInboxAgentId: __t.option(__t.string()),
  masumiAgentIdentifier: __t.option(__t.string()),
  masumiRegistrationState: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentRow = __Infer<typeof VisibleAgentRow>;

export const VisibleAgents = __t.object("VisibleAgents", {});
export type VisibleAgents = __Infer<typeof VisibleAgents>;

export const VisibleChannelJoinRequestRow = __t.object("VisibleChannelJoinRequestRow", {
  id: __t.u64(),
  channelId: __t.u64(),
  channelSlug: __t.string(),
  channelTitle: __t.option(__t.string()),
  requesterAgentDbId: __t.u64(),
  requesterPublicIdentity: __t.string(),
  requesterSlug: __t.string(),
  requesterDisplayName: __t.option(__t.string()),
  requesterCurrentEncryptionPublicKey: __t.string(),
  requesterCurrentEncryptionKeyVersion: __t.string(),
  permission: __t.string(),
  status: __t.string(),
  direction: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type VisibleChannelJoinRequestRow = __Infer<typeof VisibleChannelJoinRequestRow>;

export const VisibleChannelJoinRequests = __t.object("VisibleChannelJoinRequests", {});
export type VisibleChannelJoinRequests = __Infer<typeof VisibleChannelJoinRequests>;

export const VisibleChannelMembershipRow = __t.object("VisibleChannelMembershipRow", {
  id: __t.u64(),
  channelId: __t.u64(),
  agentDbId: __t.u64(),
  permission: __t.string(),
  active: __t.bool(),
  lastSentSeq: __t.u64(),
  joinedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleChannelMembershipRow = __Infer<typeof VisibleChannelMembershipRow>;

export const VisibleChannelMemberships = __t.object("VisibleChannelMemberships", {});
export type VisibleChannelMemberships = __Infer<typeof VisibleChannelMemberships>;

export const VisibleChannelMessageRow = __t.object("VisibleChannelMessageRow", {
  id: __t.u64(),
  channelId: __t.u64(),
  channelSeq: __t.u64(),
  senderAgentDbId: __t.u64(),
  senderPublicIdentity: __t.string(),
  senderSeq: __t.u64(),
  senderSigningPublicKey: __t.string(),
  senderSigningKeyVersion: __t.string(),
  plaintext: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type VisibleChannelMessageRow = __Infer<typeof VisibleChannelMessageRow>;

export const VisibleChannelMessages = __t.object("VisibleChannelMessages", {});
export type VisibleChannelMessages = __Infer<typeof VisibleChannelMessages>;

export const VisibleChannelRow = __t.object("VisibleChannelRow", {
  id: __t.u64(),
  slug: __t.string(),
  title: __t.option(__t.string()),
  description: __t.option(__t.string()),
  accessMode: __t.string(),
  publicJoinPermission: __t.string(),
  discoverable: __t.bool(),
  creatorAgentDbId: __t.u64(),
  lastMessageSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
});
export type VisibleChannelRow = __Infer<typeof VisibleChannelRow>;

export const VisibleChannels = __t.object("VisibleChannels", {});
export type VisibleChannels = __Infer<typeof VisibleChannels>;

export const VisibleContactAllowlistEntries = __t.object("VisibleContactAllowlistEntries", {});
export type VisibleContactAllowlistEntries = __Infer<typeof VisibleContactAllowlistEntries>;

export const VisibleContactAllowlistEntryRow = __t.object("VisibleContactAllowlistEntryRow", {
  id: __t.u64(),
  inboxId: __t.u64(),
  kind: __t.string(),
  agentPublicIdentity: __t.option(__t.string()),
  agentSlug: __t.option(__t.string()),
  agentDisplayName: __t.option(__t.string()),
  normalizedEmail: __t.option(__t.string()),
  displayEmail: __t.option(__t.string()),
  createdByAgentDbId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type VisibleContactAllowlistEntryRow = __Infer<typeof VisibleContactAllowlistEntryRow>;

export const VisibleContactRequestRow = __t.object("VisibleContactRequestRow", {
  id: __t.u64(),
  threadId: __t.u64(),
  requesterAgentDbId: __t.u64(),
  requesterPublicIdentity: __t.string(),
  requesterSlug: __t.string(),
  requesterDisplayName: __t.option(__t.string()),
  requesterNormalizedEmail: __t.string(),
  requesterDisplayEmail: __t.string(),
  requesterLinkedEmail: __t.option(__t.string()),
  targetAgentDbId: __t.u64(),
  targetPublicIdentity: __t.string(),
  targetSlug: __t.string(),
  targetDisplayName: __t.option(__t.string()),
  targetLinkedEmail: __t.option(__t.string()),
  direction: __t.string(),
  status: __t.string(),
  messageCount: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type VisibleContactRequestRow = __Infer<typeof VisibleContactRequestRow>;

export const VisibleContactRequests = __t.object("VisibleContactRequests", {});
export type VisibleContactRequests = __Infer<typeof VisibleContactRequests>;

export const VisibleDeviceKeyBundleRow = __t.object("VisibleDeviceKeyBundleRow", {
  id: __t.u64(),
  targetDeviceId: __t.string(),
  sourceDeviceId: __t.option(__t.string()),
  sourceEncryptionPublicKey: __t.string(),
  sourceEncryptionKeyVersion: __t.string(),
  sourceEncryptionAlgorithm: __t.string(),
  bundleAlgorithm: __t.string(),
  sharedAgentCount: __t.u64(),
  sharedKeyVersionCount: __t.u64(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  consumedAt: __t.option(__t.timestamp()),
  get expiryMode() {
    return DeviceKeyBundleExpiryMode;
  },
});
export type VisibleDeviceKeyBundleRow = __Infer<typeof VisibleDeviceKeyBundleRow>;

export const VisibleDeviceKeyBundles = __t.object("VisibleDeviceKeyBundles", {});
export type VisibleDeviceKeyBundles = __Infer<typeof VisibleDeviceKeyBundles>;

export const VisibleDeviceRow = __t.object("VisibleDeviceRow", {
  id: __t.u64(),
  deviceId: __t.string(),
  inboxId: __t.u64(),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  deviceEncryptionPublicKey: __t.string(),
  deviceEncryptionKeyVersion: __t.string(),
  deviceEncryptionAlgorithm: __t.string(),
  status: __t.string(),
  approvedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type VisibleDeviceRow = __Infer<typeof VisibleDeviceRow>;

export const VisibleDeviceShareRequestRow = __t.object("VisibleDeviceShareRequestRow", {
  id: __t.u64(),
  deviceId: __t.string(),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  clientCreatedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  approvedAt: __t.option(__t.timestamp()),
  consumedAt: __t.option(__t.timestamp()),
});
export type VisibleDeviceShareRequestRow = __Infer<typeof VisibleDeviceShareRequestRow>;

export const VisibleDeviceShareRequests = __t.object("VisibleDeviceShareRequests", {});
export type VisibleDeviceShareRequests = __Infer<typeof VisibleDeviceShareRequests>;

export const VisibleDevices = __t.object("VisibleDevices", {});
export type VisibleDevices = __Infer<typeof VisibleDevices>;

export const VisibleInboxRow = __t.object("VisibleInboxRow", {
  id: __t.u64(),
  normalizedEmail: __t.string(),
  displayEmail: __t.string(),
  ownerIdentity: __t.identity(),
  authSubject: __t.string(),
  authIssuer: __t.string(),
  authVerified: __t.bool(),
  emailAttested: __t.bool(),
  authVerifiedAt: __t.timestamp(),
  authExpiresAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleInboxRow = __Infer<typeof VisibleInboxRow>;

export const VisibleInboxes = __t.object("VisibleInboxes", {});
export type VisibleInboxes = __Infer<typeof VisibleInboxes>;

export const VisibleMessageRow = __t.object("VisibleMessageRow", {
  id: __t.u64(),
  threadId: __t.u64(),
  threadSeq: __t.u64(),
  membershipVersion: __t.u64(),
  senderAgentDbId: __t.u64(),
  senderSeq: __t.u64(),
  secretVersion: __t.string(),
  secretVersionStart: __t.bool(),
  signingKeyVersion: __t.string(),
  ciphertext: __t.string(),
  iv: __t.string(),
  cipherAlgorithm: __t.string(),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type VisibleMessageRow = __Infer<typeof VisibleMessageRow>;

export const VisibleMessages = __t.object("VisibleMessages", {});
export type VisibleMessages = __Infer<typeof VisibleMessages>;

export const VisibleThreadInviteRow = __t.object("VisibleThreadInviteRow", {
  id: __t.u64(),
  threadId: __t.u64(),
  inviterAgentDbId: __t.u64(),
  inviterPublicIdentity: __t.string(),
  inviterSlug: __t.string(),
  inviterDisplayName: __t.option(__t.string()),
  inviteeAgentDbId: __t.u64(),
  inviteePublicIdentity: __t.string(),
  inviteeSlug: __t.string(),
  inviteeDisplayName: __t.option(__t.string()),
  threadTitle: __t.option(__t.string()),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type VisibleThreadInviteRow = __Infer<typeof VisibleThreadInviteRow>;

export const VisibleThreadInvites = __t.object("VisibleThreadInvites", {});
export type VisibleThreadInvites = __Infer<typeof VisibleThreadInvites>;

export const VisibleThreadParticipantRow = __t.object("VisibleThreadParticipantRow", {
  id: __t.u64(),
  threadId: __t.u64(),
  agentDbId: __t.u64(),
  joinedAt: __t.timestamp(),
  lastSentSeq: __t.u64(),
  lastSentMembershipVersion: __t.option(__t.u64()),
  lastSentSecretVersion: __t.option(__t.string()),
  isAdmin: __t.bool(),
  active: __t.bool(),
});
export type VisibleThreadParticipantRow = __Infer<typeof VisibleThreadParticipantRow>;

export const VisibleThreadParticipants = __t.object("VisibleThreadParticipants", {});
export type VisibleThreadParticipants = __Infer<typeof VisibleThreadParticipants>;

export const VisibleThreadReadStateRow = __t.object("VisibleThreadReadStateRow", {
  id: __t.u64(),
  threadId: __t.u64(),
  agentDbId: __t.u64(),
  lastReadThreadSeq: __t.option(__t.u64()),
  archived: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type VisibleThreadReadStateRow = __Infer<typeof VisibleThreadReadStateRow>;

export const VisibleThreadReadStates = __t.object("VisibleThreadReadStates", {});
export type VisibleThreadReadStates = __Infer<typeof VisibleThreadReadStates>;

export const VisibleThreadRow = __t.object("VisibleThreadRow", {
  id: __t.u64(),
  dedupeKey: __t.string(),
  kind: __t.string(),
  membershipLocked: __t.bool(),
  title: __t.option(__t.string()),
  creatorAgentDbId: __t.u64(),
  membershipVersion: __t.u64(),
  nextThreadSeq: __t.u64(),
  lastMessageSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
});
export type VisibleThreadRow = __Infer<typeof VisibleThreadRow>;

export const VisibleThreadSecretEnvelopeRow = __t.object("VisibleThreadSecretEnvelopeRow", {
  id: __t.u64(),
  threadId: __t.u64(),
  membershipVersion: __t.u64(),
  secretVersion: __t.string(),
  senderAgentDbId: __t.u64(),
  recipientAgentDbId: __t.u64(),
  senderEncryptionKeyVersion: __t.string(),
  recipientEncryptionKeyVersion: __t.string(),
  signingKeyVersion: __t.string(),
  wrappedSecretCiphertext: __t.string(),
  wrappedSecretIv: __t.string(),
  wrapAlgorithm: __t.string(),
  signature: __t.string(),
  createdAt: __t.timestamp(),
});
export type VisibleThreadSecretEnvelopeRow = __Infer<typeof VisibleThreadSecretEnvelopeRow>;

export const VisibleThreadSecretEnvelopes = __t.object("VisibleThreadSecretEnvelopes", {});
export type VisibleThreadSecretEnvelopes = __Infer<typeof VisibleThreadSecretEnvelopes>;

export const VisibleThreads = __t.object("VisibleThreads", {});
export type VisibleThreads = __Infer<typeof VisibleThreads>;

