// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  email: __t.string(),
  authIdentityKey: __t.string(),
  authSubject: __t.string(),
  authIssuer: __t.string(),
  authVerifiedAt: __t.timestamp(),
  authExpiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AccountAuthLease = __t.object("AccountAuthLease", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  accountId: __t.u64(),
  expiresAt: __t.timestamp(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AccountAuthLease = __Infer<typeof AccountAuthLease>;

export const AccountChangeSignal = __t.object("AccountChangeSignal", {
  id: __t.u64(),
  accountId: __t.u64(),
  ownedAgentsVersion: __t.u64(),
  ownedDevicesVersion: __t.u64(),
  contactRequestsVersion: __t.u64(),
  threadInvitesVersion: __t.u64(),
  contactAllowlistVersion: __t.u64(),
  channelJoinRequestsVersion: __t.u64(),
  threadListVersion: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AccountChangeSignal = __Infer<typeof AccountChangeSignal>;

export const Agent = __t.object("Agent", {
  id: __t.u64(),
  accountId: __t.u64(),
  slug: __t.string(),
  publicIdentity: __t.string(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  publicDescription: __t.option(__t.string()),
  isDefault: __t.bool(),
  publicLinkedEmailEnabled: __t.bool(),
  allowAllMessageContentTypes: __t.bool(),
  allowAllMessageHeaders: __t.bool(),
  supportedMessageContentTypes: __t.array(__t.string()),
  supportedMessageHeaderNames: __t.array(__t.string()),
  masumiRegistrationNetwork: __t.option(__t.string()),
  masumiInboxAgentId: __t.option(__t.string()),
  masumiAgentIdentifier: __t.option(__t.string()),
  get masumiRegistrationState() {
    return __t.option(MasumiRegistrationState);
  },
  currentKeyBundleVersion: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentKeyBundle = __t.object("AgentKeyBundle", {
  id: __t.u64(),
  agentDbId: __t.u64(),
  keyBundleVersion: __t.u32(),
  encryptionPublicKey: __t.string(),
  get encryptionAlgorithm() {
    return EncryptionAlgorithm;
  },
  signingPublicKey: __t.string(),
  get signingAlgorithm() {
    return SigningAlgorithm;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentKeyBundle = __Infer<typeof AgentKeyBundle>;

export const AgentKeyBundleLookupRequest = __t.object("AgentKeyBundleLookupRequest", {
  agentDbId: __t.u64(),
  keyBundleVersion: __t.u32(),
});
export type AgentKeyBundleLookupRequest = __Infer<typeof AgentKeyBundleLookupRequest>;

// The tagged union or sum type for the algebraic type `AgentPublicKeyKind`.
export const AgentPublicKeyKind = __t.enum("AgentPublicKeyKind", {
  Encryption: __t.unit(),
  Signing: __t.unit(),
});
export type AgentPublicKeyKind = __Infer<typeof AgentPublicKeyKind>;

export const AgentPublicKeyLookupRequest = __t.object("AgentPublicKeyLookupRequest", {
  agentDbId: __t.u64(),
  get keyKind() {
    return AgentPublicKeyKind;
  },
  keyVersion: __t.u32(),
});
export type AgentPublicKeyLookupRequest = __Infer<typeof AgentPublicKeyLookupRequest>;

export const AgentPublicKeyLookupRow = __t.object("AgentPublicKeyLookupRow", {
  agentDbId: __t.u64(),
  get keyKind() {
    return AgentPublicKeyKind;
  },
  keyVersion: __t.u32(),
  publicKey: __t.string(),
  algorithm: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentPublicKeyLookupRow = __Infer<typeof AgentPublicKeyLookupRow>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  slug: __t.string(),
  title: __t.option(__t.string()),
  description: __t.option(__t.string()),
  get accessMode() {
    return ChannelAccessMode;
  },
  discoverable: __t.bool(),
  publicDiscoverableSortKey: __t.i64(),
  publicDiscoverableIdDescSortKey: __t.u64(),
  publicDiscoverablePageSortKey: __t.string(),
  get defaultPermission() {
    return ChannelPermission;
  },
  creatorAgentDbId: __t.u64(),
  lastMessageId: __t.u64(),
  messageCount: __t.u64(),
  lastMessageAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

// The tagged union or sum type for the algebraic type `ChannelAccessMode`.
export const ChannelAccessMode = __t.enum("ChannelAccessMode", {
  Public: __t.unit(),
  ApprovalRequired: __t.unit(),
});
export type ChannelAccessMode = __Infer<typeof ChannelAccessMode>;

export const ChannelAccountMembership = __t.object("ChannelAccountMembership", {
  id: __t.u64(),
  channelId: __t.u64(),
  accountId: __t.u64(),
  activeAgentCount: __t.u64(),
  activeAdminCount: __t.u64(),
  activeRecencySortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelAccountMembership = __Infer<typeof ChannelAccountMembership>;

export const ChannelJoinRequest = __t.object("ChannelJoinRequest", {
  id: __t.u64(),
  channelId: __t.u64(),
  requesterAgentDbId: __t.u64(),
  requesterAccountId: __t.u64(),
  get permission() {
    return ChannelPermission;
  },
  get status() {
    return ChannelJoinRequestStatus;
  },
  channelResolvedSortKey: __t.i64(),
  requesterResolvedSortKey: __t.i64(),
  channelPendingSortKey: __t.i64(),
  requesterPendingSortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type ChannelJoinRequest = __Infer<typeof ChannelJoinRequest>;

export const ChannelJoinRequestAdminVisibility = __t.object("ChannelJoinRequestAdminVisibility", {
  id: __t.u64(),
  requestId: __t.u64(),
  channelId: __t.u64(),
  adminAccountId: __t.u64(),
  pendingSortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelJoinRequestAdminVisibility = __Infer<typeof ChannelJoinRequestAdminVisibility>;

export const ChannelJoinRequestAdminVisibilityFanout = __t.object("ChannelJoinRequestAdminVisibilityFanout", {
  id: __t.u64(),
  requestId: __t.u64(),
  channelId: __t.u64(),
  nextAccountMembershipId: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelJoinRequestAdminVisibilityFanout = __Infer<typeof ChannelJoinRequestAdminVisibilityFanout>;

export const ChannelJoinRequestResolvedAdminVisibility = __t.object("ChannelJoinRequestResolvedAdminVisibility", {
  id: __t.u64(),
  requestId: __t.u64(),
  channelId: __t.u64(),
  adminAccountId: __t.u64(),
  resolvedSortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelJoinRequestResolvedAdminVisibility = __Infer<typeof ChannelJoinRequestResolvedAdminVisibility>;

export const ChannelJoinRequestResolvedAdminVisibilityFanout = __t.object("ChannelJoinRequestResolvedAdminVisibilityFanout", {
  id: __t.u64(),
  requestId: __t.u64(),
  channelId: __t.u64(),
  resolvedSortKey: __t.i64(),
  nextAccountMembershipId: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelJoinRequestResolvedAdminVisibilityFanout = __Infer<typeof ChannelJoinRequestResolvedAdminVisibilityFanout>;

// The tagged union or sum type for the algebraic type `ChannelJoinRequestStatus`.
export const ChannelJoinRequestStatus = __t.enum("ChannelJoinRequestStatus", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Rejected: __t.unit(),
});
export type ChannelJoinRequestStatus = __Infer<typeof ChannelJoinRequestStatus>;

export const ChannelMember = __t.object("ChannelMember", {
  id: __t.u64(),
  channelId: __t.u64(),
  agentDbId: __t.u64(),
  accountId: __t.u64(),
  get permission() {
    return ChannelPermission;
  },
  active: __t.bool(),
  activeRecencySortKey: __t.i64(),
  lastSentSeq: __t.u64(),
  lastReadMessageId: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelMember = __Infer<typeof ChannelMember>;

export const ChannelMessage = __t.object("ChannelMessage", {
  id: __t.u64(),
  channelId: __t.u64(),
  idDescSortKey: __t.u64(),
  senderAgentDbId: __t.u64(),
  senderPublicIdentity: __t.string(),
  senderSigningKeyVersion: __t.u32(),
  senderMessageId: __t.u64(),
  plaintext: __t.string(),
  signature: __t.byteArray(),
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelMessage = __Infer<typeof ChannelMessage>;

// The tagged union or sum type for the algebraic type `ChannelPermission`.
export const ChannelPermission = __t.enum("ChannelPermission", {
  Read: __t.unit(),
  ReadWrite: __t.unit(),
  Admin: __t.unit(),
});
export type ChannelPermission = __Infer<typeof ChannelPermission>;

export const ChannelRecencyFanout = __t.object("ChannelRecencyFanout", {
  id: __t.u64(),
  channelId: __t.u64(),
  targetRecencySortKey: __t.i64(),
  nextAccountMembershipId: __t.u64(),
  restartRequested: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ChannelRecencyFanout = __Infer<typeof ChannelRecencyFanout>;

export const ContactAllowlistEntry = __t.object("ContactAllowlistEntry", {
  id: __t.u64(),
  accountId: __t.u64(),
  get kind() {
    return ContactAllowlistKind;
  },
  lookupKey: __t.string(),
  agentPublicIdentity: __t.option(__t.string()),
  agentSlug: __t.option(__t.string()),
  email: __t.option(__t.string()),
  createdByAgentDbId: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ContactAllowlistEntry = __Infer<typeof ContactAllowlistEntry>;

// The tagged union or sum type for the algebraic type `ContactAllowlistKind`.
export const ContactAllowlistKind = __t.enum("ContactAllowlistKind", {
  Agent: __t.unit(),
  Email: __t.unit(),
});
export type ContactAllowlistKind = __Infer<typeof ContactAllowlistKind>;

export const ContactRequest = __t.object("ContactRequest", {
  id: __t.u64(),
  threadId: __t.u64(),
  requesterAgentDbId: __t.u64(),
  targetAgentDbId: __t.u64(),
  requesterAccountId: __t.u64(),
  targetAccountId: __t.u64(),
  requesterPublicIdentity: __t.string(),
  requesterSlug: __t.string(),
  targetPublicIdentity: __t.string(),
  targetSlug: __t.string(),
  get status() {
    return ContactRequestStatus;
  },
  requesterResolvedSortKey: __t.i64(),
  targetResolvedSortKey: __t.i64(),
  requesterPendingSortKey: __t.i64(),
  targetPendingSortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
  requesterHiddenAt: __t.option(__t.timestamp()),
});
export type ContactRequest = __Infer<typeof ContactRequest>;

// The tagged union or sum type for the algebraic type `ContactRequestStatus`.
export const ContactRequestStatus = __t.enum("ContactRequestStatus", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Rejected: __t.unit(),
  Cancelled: __t.unit(),
});
export type ContactRequestStatus = __Infer<typeof ContactRequestStatus>;

export const Device = __t.object("Device", {
  id: __t.u64(),
  accountId: __t.u64(),
  deviceId: __t.string(),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  deviceEncryptionPublicKey: __t.string(),
  deviceEncryptionKeyVersion: __t.u32(),
  get deviceEncryptionAlgorithm() {
    return DeviceEncryptionAlgorithm;
  },
  get status() {
    return DeviceStatus;
  },
  approvedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
  lastSeenAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Device = __Infer<typeof Device>;

// The tagged union or sum type for the algebraic type `DeviceBundleAlgorithm`.
export const DeviceBundleAlgorithm = __t.enum("DeviceBundleAlgorithm", {
  AesGcm256V1: __t.unit(),
});
export type DeviceBundleAlgorithm = __Infer<typeof DeviceBundleAlgorithm>;

// The tagged union or sum type for the algebraic type `DeviceEncryptionAlgorithm`.
export const DeviceEncryptionAlgorithm = __t.enum("DeviceEncryptionAlgorithm", {
  EcdhP256DeviceV1: __t.unit(),
});
export type DeviceEncryptionAlgorithm = __Infer<typeof DeviceEncryptionAlgorithm>;

export const DeviceKeyBundle = __t.object("DeviceKeyBundle", {
  id: __t.u64(),
  targetDeviceId: __t.string(),
  sourceDeviceId: __t.string(),
  accountId: __t.u64(),
  sourceEncryptionPublicKey: __t.string(),
  sourceEncryptionKeyVersion: __t.u32(),
  get sourceEncryptionAlgorithm() {
    return DeviceEncryptionAlgorithm;
  },
  bundleCiphertext: __t.byteArray(),
  bundleIv: __t.byteArray(),
  get bundleAlgorithm() {
    return DeviceBundleAlgorithm;
  },
  get purpose() {
    return DeviceKeyBundlePurpose;
  },
  sharedAgentCount: __t.u64(),
  sharedKeyVersionCount: __t.u64(),
  expiresAt: __t.timestamp(),
  consumedAt: __t.option(__t.timestamp()),
  pendingSortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DeviceKeyBundle = __Infer<typeof DeviceKeyBundle>;

// The tagged union or sum type for the algebraic type `DeviceKeyBundlePurpose`.
export const DeviceKeyBundlePurpose = __t.enum("DeviceKeyBundlePurpose", {
  InitialOnboarding: __t.unit(),
  RotationShare: __t.unit(),
});
export type DeviceKeyBundlePurpose = __Infer<typeof DeviceKeyBundlePurpose>;

export const DeviceShareRequest = __t.object("DeviceShareRequest", {
  id: __t.u64(),
  deviceId: __t.string(),
  accountId: __t.u64(),
  verificationCodeHash: __t.string(),
  clientCreatedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  approvedAt: __t.option(__t.timestamp()),
  consumedAt: __t.option(__t.timestamp()),
  pendingSortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DeviceShareRequest = __Infer<typeof DeviceShareRequest>;

// The tagged union or sum type for the algebraic type `DeviceStatus`.
export const DeviceStatus = __t.enum("DeviceStatus", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Revoked: __t.unit(),
});
export type DeviceStatus = __Infer<typeof DeviceStatus>;

// The tagged union or sum type for the algebraic type `EncryptionAlgorithm`.
export const EncryptionAlgorithm = __t.enum("EncryptionAlgorithm", {
  EcdhP256V1: __t.unit(),
});
export type EncryptionAlgorithm = __Infer<typeof EncryptionAlgorithm>;

export const ListThreadMessagesPage = __t.object("ListThreadMessagesPage", {
  get messages() {
    return __t.array(Message);
  },
  get secretEnvelopes() {
    return __t.array(ThreadSecretEnvelope);
  },
  nextBeforeMessageId: __t.option(__t.u64()),
});
export type ListThreadMessagesPage = __Infer<typeof ListThreadMessagesPage>;

// The tagged union or sum type for the algebraic type `MasumiRegistrationState`.
export const MasumiRegistrationState = __t.enum("MasumiRegistrationState", {
  PendingRegistration: __t.unit(),
  Registered: __t.unit(),
  PendingDeregistration: __t.unit(),
  Deregistered: __t.unit(),
  Failed: __t.unit(),
});
export type MasumiRegistrationState = __Infer<typeof MasumiRegistrationState>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  threadId: __t.u64(),
  idDescSortKey: __t.u64(),
  senderAgentDbId: __t.u64(),
  senderMessageId: __t.u64(),
  secretVersion: __t.u32(),
  attachesNewEnvelopes: __t.bool(),
  membershipVersion: __t.u64(),
  signingKeyVersion: __t.u32(),
  ciphertext: __t.byteArray(),
  iv: __t.byteArray(),
  signature: __t.byteArray(),
  get cipherAlgorithm() {
    return MessageCipherAlgorithm;
  },
  replyToMessageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

// The tagged union or sum type for the algebraic type `MessageCipherAlgorithm`.
export const MessageCipherAlgorithm = __t.enum("MessageCipherAlgorithm", {
  AesGcm256V1: __t.unit(),
});
export type MessageCipherAlgorithm = __Infer<typeof MessageCipherAlgorithm>;

export const OwnedAgentPage = __t.object("OwnedAgentPage", {
  get agents() {
    return __t.array(Agent);
  },
  nextAfterId: __t.option(__t.u64()),
});
export type OwnedAgentPage = __Infer<typeof OwnedAgentPage>;

export const PendingChannelJoinRequestPage = __t.object("PendingChannelJoinRequestPage", {
  get joinRequests() {
    return __t.array(ChannelJoinRequest);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type PendingChannelJoinRequestPage = __Infer<typeof PendingChannelJoinRequestPage>;

export const PendingContactRequestPage = __t.object("PendingContactRequestPage", {
  get contactRequests() {
    return __t.array(ContactRequest);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type PendingContactRequestPage = __Infer<typeof PendingContactRequestPage>;

export const PendingThreadInvitePage = __t.object("PendingThreadInvitePage", {
  get threadInvites() {
    return __t.array(ThreadInvite);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type PendingThreadInvitePage = __Infer<typeof PendingThreadInvitePage>;

export const PublishedAgentLookupRow = __t.object("PublishedAgentLookupRow", {
  agentDbId: __t.u64(),
  slug: __t.string(),
  publicIdentity: __t.string(),
  displayName: __t.option(__t.string()),
  isDefault: __t.bool(),
  linkedEmail: __t.option(__t.string()),
  agentIdentifier: __t.option(__t.string()),
  encryptionKeyVersion: __t.u32(),
  encryptionAlgorithm: __t.string(),
  encryptionPublicKey: __t.string(),
  signingKeyVersion: __t.u32(),
  signingAlgorithm: __t.string(),
  signingPublicKey: __t.string(),
});
export type PublishedAgentLookupRow = __Infer<typeof PublishedAgentLookupRow>;

export const PublishedAgentSigningKeyLookupRequest = __t.object("PublishedAgentSigningKeyLookupRequest", {
  agentDbId: __t.u64(),
  signingKeyVersion: __t.u32(),
});
export type PublishedAgentSigningKeyLookupRequest = __Infer<typeof PublishedAgentSigningKeyLookupRequest>;

export const PublishedAgentSigningKeyLookupRow = __t.object("PublishedAgentSigningKeyLookupRow", {
  agentDbId: __t.u64(),
  signingKeyVersion: __t.u32(),
  signingPublicKey: __t.string(),
});
export type PublishedAgentSigningKeyLookupRow = __Infer<typeof PublishedAgentSigningKeyLookupRow>;

export const PublishedPublicRouteContactPolicy = __t.object("PublishedPublicRouteContactPolicy", {
  mode: __t.string(),
  allowlistScope: __t.string(),
  allowlistKinds: __t.array(__t.string()),
  messagePreviewVisibleBeforeApproval: __t.bool(),
});
export type PublishedPublicRouteContactPolicy = __Infer<typeof PublishedPublicRouteContactPolicy>;

export const PublishedPublicRouteHeaderCapability = __t.object("PublishedPublicRouteHeaderCapability", {
  name: __t.string(),
  required: __t.option(__t.bool()),
  allowMultiple: __t.option(__t.bool()),
  sensitive: __t.option(__t.bool()),
  allowedPrefixes: __t.option(__t.array(__t.string())),
});
export type PublishedPublicRouteHeaderCapability = __Infer<typeof PublishedPublicRouteHeaderCapability>;

export const PublishedPublicRouteRow = __t.object("PublishedPublicRouteRow", {
  slug: __t.string(),
  publicIdentity: __t.string(),
  displayName: __t.option(__t.string()),
  description: __t.option(__t.string()),
  publicLinkedEmailEnabled: __t.bool(),
  linkedEmail: __t.option(__t.string()),
  agentIdentifier: __t.option(__t.string()),
  encryptionKeyVersion: __t.u32(),
  encryptionAlgorithm: __t.string(),
  encryptionPublicKey: __t.string(),
  signingKeyVersion: __t.u32(),
  signingAlgorithm: __t.string(),
  signingPublicKey: __t.string(),
  allowAllContentTypes: __t.bool(),
  allowAllHeaders: __t.bool(),
  supportedContentTypes: __t.array(__t.string()),
  get supportedHeaders() {
    return __t.array(PublishedPublicRouteHeaderCapability);
  },
  get contactPolicy() {
    return PublishedPublicRouteContactPolicy;
  },
});
export type PublishedPublicRouteRow = __Infer<typeof PublishedPublicRouteRow>;

export const RateLimit = __t.object("RateLimit", {
  id: __t.u64(),
  bucketKey: __t.string(),
  get action() {
    return RateLimitAction;
  },
  ownerIdentity: __t.identity(),
  windowStart: __t.timestamp(),
  expiresAt: __t.timestamp(),
  count: __t.u64(),
  limitedCount: __t.u64(),
  firstLimitedAt: __t.option(__t.timestamp()),
  lastLimitedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RateLimit = __Infer<typeof RateLimit>;

// The tagged union or sum type for the algebraic type `RateLimitAction`.
export const RateLimitAction = __t.enum("RateLimitAction", {
  EmailLookup: __t.unit(),
  DeviceShareRequest: __t.unit(),
  DeviceShareResolve: __t.unit(),
  PublicChannelLookup: __t.unit(),
  PublicAgentLookup: __t.unit(),
  PublicKeyLookup: __t.unit(),
  PublicRouteLookup: __t.unit(),
  ThreadMessage: __t.unit(),
  ChannelMessage: __t.unit(),
  ChannelJoinRequest: __t.unit(),
  ChannelJoin: __t.unit(),
  ChannelCreate: __t.unit(),
  ChannelAdmin: __t.unit(),
  ThreadAdmin: __t.unit(),
  AgentKeyRotate: __t.unit(),
  DeviceBundleShare: __t.unit(),
  ContactRequest: __t.unit(),
  ContactResolve: __t.unit(),
});
export type RateLimitAction = __Infer<typeof RateLimitAction>;

export const ResolvedChannelJoinRequestPage = __t.object("ResolvedChannelJoinRequestPage", {
  get joinRequests() {
    return __t.array(ChannelJoinRequest);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type ResolvedChannelJoinRequestPage = __Infer<typeof ResolvedChannelJoinRequestPage>;

export const ResolvedContactRequestPage = __t.object("ResolvedContactRequestPage", {
  get contactRequests() {
    return __t.array(ContactRequest);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type ResolvedContactRequestPage = __Infer<typeof ResolvedContactRequestPage>;

export const ResolvedDeviceShareRequestRow = __t.object("ResolvedDeviceShareRequestRow", {
  requestId: __t.u64(),
  deviceId: __t.string(),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  deviceEncryptionPublicKey: __t.string(),
  deviceEncryptionKeyVersion: __t.u32(),
  deviceEncryptionAlgorithm: __t.string(),
  clientCreatedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type ResolvedDeviceShareRequestRow = __Infer<typeof ResolvedDeviceShareRequestRow>;

export const ResolvedThreadInvitePage = __t.object("ResolvedThreadInvitePage", {
  get threadInvites() {
    return __t.array(ThreadInvite);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type ResolvedThreadInvitePage = __Infer<typeof ResolvedThreadInvitePage>;

export const ScheduledExpiry = __t.object("ScheduledExpiry", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  get kind() {
    return ScheduledExpiryKind;
  },
  targetId: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ScheduledExpiry = __Infer<typeof ScheduledExpiry>;

// The tagged union or sum type for the algebraic type `ScheduledExpiryKind`.
export const ScheduledExpiryKind = __t.enum("ScheduledExpiryKind", {
  DeviceShareRequest: __t.unit(),
  DeviceKeyBundle: __t.unit(),
  AccountAuthLease: __t.unit(),
  RateLimit: __t.unit(),
  ThreadDeletionCleanup: __t.unit(),
  ThreadDeletionCleanupPreserveContactRequests: __t.unit(),
  MessageExpiry: __t.unit(),
  ThreadSecretEnvelopeGc: __t.unit(),
  AgentKeyBundleArchive: __t.unit(),
  ResolvedRequestTombstone: __t.unit(),
  ChannelRecencyFanout: __t.unit(),
  ChannelJoinRequestAdminVisibilityFanout: __t.unit(),
  ChannelJoinRequestResolvedAdminVisibilityFanout: __t.unit(),
});
export type ScheduledExpiryKind = __Infer<typeof ScheduledExpiryKind>;

export const SecretEnvelopeAttachment = __t.object("SecretEnvelopeAttachment", {
  recipientPublicIdentity: __t.string(),
  recipientEncryptionKeyVersion: __t.u32(),
  senderEncryptionKeyVersion: __t.u32(),
  signingKeyVersion: __t.u32(),
  wrappedSecretCiphertext: __t.byteArray(),
  wrappedSecretIv: __t.byteArray(),
  get wrapAlgorithm() {
    return ThreadSecretWrapAlgorithm;
  },
  signature: __t.byteArray(),
});
export type SecretEnvelopeAttachment = __Infer<typeof SecretEnvelopeAttachment>;

// The tagged union or sum type for the algebraic type `SigningAlgorithm`.
export const SigningAlgorithm = __t.enum("SigningAlgorithm", {
  EcdsaP256Sha256V1: __t.unit(),
});
export type SigningAlgorithm = __Infer<typeof SigningAlgorithm>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  get kind() {
    return ThreadKind;
  },
  directLowAgentDbId: __t.u64(),
  directHighAgentDbId: __t.u64(),
  title: __t.option(__t.string()),
  creatorAgentDbId: __t.u64(),
  membershipVersion: __t.u64(),
  activeParticipantCount: __t.u64(),
  lastMessageId: __t.u64(),
  messageCount: __t.u64(),
  lastMessageAt: __t.timestamp(),
  messageRetentionMs: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Thread = __Infer<typeof Thread>;

export const ThreadInvite = __t.object("ThreadInvite", {
  id: __t.u64(),
  threadId: __t.u64(),
  inviterAgentDbId: __t.u64(),
  inviterAccountId: __t.u64(),
  inviteeAgentDbId: __t.u64(),
  inviteeAccountId: __t.u64(),
  get status() {
    return ThreadInviteStatus;
  },
  inviterResolvedSortKey: __t.i64(),
  inviteeResolvedSortKey: __t.i64(),
  inviteePendingSortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedByAgentDbId: __t.option(__t.u64()),
});
export type ThreadInvite = __Infer<typeof ThreadInvite>;

// The tagged union or sum type for the algebraic type `ThreadInviteStatus`.
export const ThreadInviteStatus = __t.enum("ThreadInviteStatus", {
  Pending: __t.unit(),
  Accepted: __t.unit(),
  Declined: __t.unit(),
});
export type ThreadInviteStatus = __Infer<typeof ThreadInviteStatus>;

// The tagged union or sum type for the algebraic type `ThreadKind`.
export const ThreadKind = __t.enum("ThreadKind", {
  Direct: __t.unit(),
  Group: __t.unit(),
});
export type ThreadKind = __Infer<typeof ThreadKind>;

export const ThreadParticipant = __t.object("ThreadParticipant", {
  id: __t.u64(),
  threadId: __t.u64(),
  agentDbId: __t.u64(),
  accountId: __t.u64(),
  membershipVersion: __t.u64(),
  lastSentSeq: __t.u64(),
  lastSentSecretVersion: __t.u32(),
  lastReadMessageId: __t.u64(),
  archived: __t.bool(),
  isAdmin: __t.bool(),
  active: __t.bool(),
  activeRecencySortKey: __t.i64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ThreadParticipant = __Infer<typeof ThreadParticipant>;

export const ThreadParticipantPage = __t.object("ThreadParticipantPage", {
  get participants() {
    return __t.array(ThreadParticipantPreview);
  },
  get actors() {
    return __t.array(VisibleAgentRow);
  },
  nextAfterId: __t.option(__t.u64()),
});
export type ThreadParticipantPage = __Infer<typeof ThreadParticipantPage>;

export const ThreadParticipantPreview = __t.object("ThreadParticipantPreview", {
  id: __t.u64(),
  threadId: __t.u64(),
  agentDbId: __t.u64(),
  accountId: __t.u64(),
  membershipVersion: __t.option(__t.u64()),
  lastSentSeq: __t.option(__t.u64()),
  lastSentSecretVersion: __t.option(__t.u32()),
  lastReadMessageId: __t.option(__t.u64()),
  archived: __t.option(__t.bool()),
  isAdmin: __t.bool(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type ThreadParticipantPreview = __Infer<typeof ThreadParticipantPreview>;

export const ThreadSecretCoverage = __t.object("ThreadSecretCoverage", {
  id: __t.u64(),
  threadId: __t.u64(),
  membershipVersion: __t.u64(),
  senderAgentDbId: __t.u64(),
  secretVersion: __t.u32(),
  participantCount: __t.u32(),
  senderKeyBundleVersion: __t.u32(),
  recipientVersionsFingerprint: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ThreadSecretCoverage = __Infer<typeof ThreadSecretCoverage>;

export const ThreadSecretEnvelope = __t.object("ThreadSecretEnvelope", {
  id: __t.u64(),
  threadId: __t.u64(),
  membershipVersion: __t.u64(),
  secretVersion: __t.u32(),
  senderAgentDbId: __t.u64(),
  recipientAgentDbId: __t.u64(),
  senderAccountId: __t.u64(),
  recipientAccountId: __t.u64(),
  senderEncryptionKeyVersion: __t.u32(),
  recipientEncryptionKeyVersion: __t.u32(),
  signingKeyVersion: __t.u32(),
  wrappedSecretCiphertext: __t.byteArray(),
  wrappedSecretIv: __t.byteArray(),
  signature: __t.byteArray(),
  get wrapAlgorithm() {
    return ThreadSecretWrapAlgorithm;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ThreadSecretEnvelope = __Infer<typeof ThreadSecretEnvelope>;

// The tagged union or sum type for the algebraic type `ThreadSecretWrapAlgorithm`.
export const ThreadSecretWrapAlgorithm = __t.enum("ThreadSecretWrapAlgorithm", {
  EcdhP256AesGcm256V1: __t.unit(),
});
export type ThreadSecretWrapAlgorithm = __Infer<typeof ThreadSecretWrapAlgorithm>;

export const VisibleAgentRow = __t.object("VisibleAgentRow", {
  id: __t.u64(),
  accountId: __t.u64(),
  slug: __t.string(),
  publicIdentity: __t.string(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  publicDescription: __t.option(__t.string()),
  isDefault: __t.bool(),
  publicLinkedEmailEnabled: __t.bool(),
  allowAllMessageContentTypes: __t.bool(),
  allowAllMessageHeaders: __t.bool(),
  supportedMessageContentTypes: __t.array(__t.string()),
  supportedMessageHeaderNames: __t.array(__t.string()),
  masumiRegistrationNetwork: __t.option(__t.string()),
  masumiInboxAgentId: __t.option(__t.string()),
  masumiAgentIdentifier: __t.option(__t.string()),
  get masumiRegistrationState() {
    return __t.option(MasumiRegistrationState);
  },
  currentKeyBundleVersion: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentRow = __Infer<typeof VisibleAgentRow>;

export const VisibleChannelPage = __t.object("VisibleChannelPage", {
  get channels() {
    return __t.array(Channel);
  },
  get accountMemberships() {
    return __t.array(ChannelAccountMembership);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type VisibleChannelPage = __Infer<typeof VisibleChannelPage>;

export const VisibleChannelState = __t.object("VisibleChannelState", {
  get channel() {
    return Channel;
  },
  get member() {
    return __t.option(ChannelMember);
  },
});
export type VisibleChannelState = __Infer<typeof VisibleChannelState>;

export const VisibleThreadPage = __t.object("VisibleThreadPage", {
  get threads() {
    return __t.array(Thread);
  },
  get participantPreviews() {
    return __t.array(ThreadParticipantPreview);
  },
  get actors() {
    return __t.array(VisibleAgentRow);
  },
  nextAfterSortKey: __t.option(__t.string()),
});
export type VisibleThreadPage = __Infer<typeof VisibleThreadPage>;

