// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  agentDbId: __t.u64(),
  displayName: __t.option(__t.string()),
  clearDisplayName: __t.option(__t.bool()),
  publicDescription: __t.option(__t.string()),
  clearPublicDescription: __t.option(__t.bool()),
  publicLinkedEmailEnabled: __t.option(__t.bool()),
};
