// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  accountId: __t.u64().name("account_id"),
  ownedAgentsVersion: __t.u64().name("owned_agents_version"),
  ownedDevicesVersion: __t.u64().name("owned_devices_version"),
  contactRequestsVersion: __t.u64().name("contact_requests_version"),
  threadInvitesVersion: __t.u64().name("thread_invites_version"),
  contactAllowlistVersion: __t.u64().name("contact_allowlist_version"),
  channelJoinRequestsVersion: __t.u64().name("channel_join_requests_version"),
  threadListVersion: __t.u64().name("thread_list_version"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
