// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  threadId: __t.u64().name("thread_id"),
  inviterAgentDbId: __t.u64().name("inviter_agent_db_id"),
  inviterPublicIdentity: __t.string().name("inviter_public_identity"),
  inviterSlug: __t.string().name("inviter_slug"),
  inviterDisplayName: __t.option(__t.string()).name("inviter_display_name"),
  inviteeAgentDbId: __t.u64().name("invitee_agent_db_id"),
  inviteePublicIdentity: __t.string().name("invitee_public_identity"),
  inviteeSlug: __t.string().name("invitee_slug"),
  inviteeDisplayName: __t.option(__t.string()).name("invitee_display_name"),
  threadTitle: __t.option(__t.string()).name("thread_title"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  resolvedByAgentDbId: __t.option(__t.u64()).name("resolved_by_agent_db_id"),
});
