// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  threadId: __t.u64().name("thread_id"),
  requesterAgentDbId: __t.u64().name("requester_agent_db_id"),
  requesterPublicIdentity: __t.string().name("requester_public_identity"),
  requesterSlug: __t.string().name("requester_slug"),
  requesterDisplayName: __t.option(__t.string()).name("requester_display_name"),
  requesterNormalizedEmail: __t.string().name("requester_normalized_email"),
  requesterDisplayEmail: __t.string().name("requester_display_email"),
  requesterLinkedEmail: __t.option(__t.string()).name("requester_linked_email"),
  targetAgentDbId: __t.u64().name("target_agent_db_id"),
  targetPublicIdentity: __t.string().name("target_public_identity"),
  targetSlug: __t.string().name("target_slug"),
  targetDisplayName: __t.option(__t.string()).name("target_display_name"),
  targetLinkedEmail: __t.option(__t.string()).name("target_linked_email"),
  direction: __t.string(),
  status: __t.string(),
  messageCount: __t.u64().name("message_count"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  resolvedByAgentDbId: __t.option(__t.u64()).name("resolved_by_agent_db_id"),
});
