// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  dedupeKey: __t.string().name("dedupe_key"),
  kind: __t.string(),
  membershipLocked: __t.bool().name("membership_locked"),
  title: __t.option(__t.string()),
  creatorAgentDbId: __t.u64().name("creator_agent_db_id"),
  membershipVersion: __t.u64().name("membership_version"),
  nextThreadSeq: __t.u64().name("next_thread_seq"),
  lastMessageSeq: __t.u64().name("last_message_seq"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  lastMessageAt: __t.timestamp().name("last_message_at"),
});
