// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  threadId: __t.u64().name("thread_id"),
  threadSeq: __t.u64().name("thread_seq"),
  membershipVersion: __t.u64().name("membership_version"),
  senderAgentDbId: __t.u64().name("sender_agent_db_id"),
  senderSeq: __t.u64().name("sender_seq"),
  secretVersion: __t.string().name("secret_version"),
  secretVersionStart: __t.bool().name("secret_version_start"),
  signingKeyVersion: __t.string().name("signing_key_version"),
  ciphertext: __t.string(),
  iv: __t.string(),
  cipherAlgorithm: __t.string().name("cipher_algorithm"),
  signature: __t.string(),
  replyToMessageId: __t.option(__t.u64()).name("reply_to_message_id"),
  createdAt: __t.timestamp().name("created_at"),
});
