// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  inboxId: __t.u64().name("inbox_id"),
  normalizedEmail: __t.string().name("normalized_email"),
  slug: __t.string(),
  inboxIdentifier: __t.option(__t.string()).name("inbox_identifier"),
  isDefault: __t.bool().name("is_default"),
  publicIdentity: __t.string().name("public_identity"),
  displayName: __t.option(__t.string()).name("display_name"),
  publicLinkedEmailEnabled: __t.bool().name("public_linked_email_enabled"),
  publicDescription: __t.option(__t.string()).name("public_description"),
  allowAllMessageContentTypes: __t.option(__t.bool()).name("allow_all_message_content_types"),
  allowAllMessageHeaders: __t.option(__t.bool()).name("allow_all_message_headers"),
  supportedMessageContentTypes: __t.option(__t.array(__t.string())).name("supported_message_content_types"),
  supportedMessageHeaderNames: __t.option(__t.array(__t.string())).name("supported_message_header_names"),
  currentEncryptionPublicKey: __t.string().name("current_encryption_public_key"),
  currentEncryptionKeyVersion: __t.string().name("current_encryption_key_version"),
  currentEncryptionAlgorithm: __t.string().name("current_encryption_algorithm"),
  currentSigningPublicKey: __t.string().name("current_signing_public_key"),
  currentSigningKeyVersion: __t.string().name("current_signing_key_version"),
  currentSigningAlgorithm: __t.string().name("current_signing_algorithm"),
  masumiRegistrationNetwork: __t.option(__t.string()).name("masumi_registration_network"),
  masumiInboxAgentId: __t.option(__t.string()).name("masumi_inbox_agent_id"),
  masumiAgentIdentifier: __t.option(__t.string()).name("masumi_agent_identifier"),
  masumiRegistrationState: __t.option(__t.string()).name("masumi_registration_state"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
