// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  threadId: __t.u64().name("thread_id"),
  agentDbId: __t.u64().name("agent_db_id"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastSentSeq: __t.u64().name("last_sent_seq"),
  lastSentMembershipVersion: __t.option(__t.u64()).name("last_sent_membership_version"),
  lastSentSecretVersion: __t.option(__t.string()).name("last_sent_secret_version"),
  isAdmin: __t.bool().name("is_admin"),
  active: __t.bool(),
});
