// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  inboxId: __t.u64().name("inbox_id"),
  kind: __t.string(),
  agentPublicIdentity: __t.option(__t.string()).name("agent_public_identity"),
  agentSlug: __t.option(__t.string()).name("agent_slug"),
  agentDisplayName: __t.option(__t.string()).name("agent_display_name"),
  normalizedEmail: __t.option(__t.string()).name("normalized_email"),
  displayEmail: __t.option(__t.string()).name("display_email"),
  createdByAgentDbId: __t.u64().name("created_by_agent_db_id"),
  createdAt: __t.timestamp().name("created_at"),
});
