// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  deviceId: __t.string().name("device_id"),
  inboxId: __t.u64().name("inbox_id"),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  deviceEncryptionPublicKey: __t.string().name("device_encryption_public_key"),
  deviceEncryptionKeyVersion: __t.string().name("device_encryption_key_version"),
  deviceEncryptionAlgorithm: __t.string().name("device_encryption_algorithm"),
  status: __t.string(),
  approvedAt: __t.option(__t.timestamp()).name("approved_at"),
  revokedAt: __t.option(__t.timestamp()).name("revoked_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
});
