// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  normalizedEmail: __t.string().name("normalized_email"),
  displayEmail: __t.string().name("display_email"),
  ownerIdentity: __t.identity().name("owner_identity"),
  authSubject: __t.string().name("auth_subject"),
  authIssuer: __t.string().name("auth_issuer"),
  authVerified: __t.bool().name("auth_verified"),
  emailAttested: __t.bool().name("email_attested"),
  authVerifiedAt: __t.timestamp().name("auth_verified_at"),
  authExpiresAt: __t.option(__t.timestamp()).name("auth_expires_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
