// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  targetDeviceId: __t.string().name("target_device_id"),
  sourceDeviceId: __t.option(__t.string()).name("source_device_id"),
  sourceEncryptionPublicKey: __t.string().name("source_encryption_public_key"),
  sourceEncryptionKeyVersion: __t.string().name("source_encryption_key_version"),
  sourceEncryptionAlgorithm: __t.string().name("source_encryption_algorithm"),
  bundleAlgorithm: __t.string().name("bundle_algorithm"),
  sharedAgentCount: __t.u64().name("shared_agent_count"),
  sharedKeyVersionCount: __t.u64().name("shared_key_version_count"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  consumedAt: __t.option(__t.timestamp()).name("consumed_at"),
});
