// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  ownerIdentity: __t.identity().name("owner_identity"),
  email: __t.string(),
  authIdentityKey: __t.string().name("auth_identity_key"),
  authSubject: __t.string().name("auth_subject"),
  authIssuer: __t.string().name("auth_issuer"),
  authVerifiedAt: __t.timestamp().name("auth_verified_at"),
  authExpiresAt: __t.timestamp().name("auth_expires_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
