// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  channelId: __t.u64().name("channel_id"),
  agentDbId: __t.u64().name("agent_db_id"),
  permission: __t.string(),
  active: __t.bool(),
  lastSentSeq: __t.u64().name("last_sent_seq"),
  joinedAt: __t.timestamp().name("joined_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
