// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  deviceId: __t.string().name("device_id"),
  label: __t.option(__t.string()),
  platform: __t.option(__t.string()),
  clientCreatedAt: __t.timestamp().name("client_created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  createdAt: __t.timestamp().name("created_at"),
  approvedAt: __t.option(__t.timestamp()).name("approved_at"),
  consumedAt: __t.option(__t.timestamp()).name("consumed_at"),
});
