// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  agentDbId: __t.u64().name("agent_db_id"),
  publicIdentity: __t.string().name("public_identity"),
  encryptionPublicKey: __t.string().name("encryption_public_key"),
  encryptionKeyVersion: __t.string().name("encryption_key_version"),
  encryptionAlgorithm: __t.string().name("encryption_algorithm"),
  signingPublicKey: __t.string().name("signing_public_key"),
  signingKeyVersion: __t.string().name("signing_key_version"),
  signingAlgorithm: __t.string().name("signing_algorithm"),
  createdAt: __t.timestamp().name("created_at"),
});
