// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  channelId: __t.u64().name("channel_id"),
  channelSlug: __t.string().name("channel_slug"),
  channelTitle: __t.option(__t.string()).name("channel_title"),
  requesterAgentDbId: __t.u64().name("requester_agent_db_id"),
  requesterPublicIdentity: __t.string().name("requester_public_identity"),
  requesterSlug: __t.string().name("requester_slug"),
  requesterDisplayName: __t.option(__t.string()).name("requester_display_name"),
  requesterCurrentEncryptionPublicKey: __t.string().name("requester_current_encryption_public_key"),
  requesterCurrentEncryptionKeyVersion: __t.string().name("requester_current_encryption_key_version"),
  permission: __t.string(),
  status: __t.string(),
  direction: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  resolvedByAgentDbId: __t.option(__t.u64()).name("resolved_by_agent_db_id"),
});
