// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  threadId: __t.u64().name("thread_id"),
  membershipVersion: __t.u64().name("membership_version"),
  secretVersion: __t.string().name("secret_version"),
  senderAgentDbId: __t.u64().name("sender_agent_db_id"),
  recipientAgentDbId: __t.u64().name("recipient_agent_db_id"),
  senderEncryptionKeyVersion: __t.string().name("sender_encryption_key_version"),
  recipientEncryptionKeyVersion: __t.string().name("recipient_encryption_key_version"),
  signingKeyVersion: __t.string().name("signing_key_version"),
  wrappedSecretCiphertext: __t.string().name("wrapped_secret_ciphertext"),
  wrappedSecretIv: __t.string().name("wrapped_secret_iv"),
  wrapAlgorithm: __t.string().name("wrap_algorithm"),
  signature: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
