// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DeviceEncryptionAlgorithm,
  DeviceBundleAlgorithm,
  DeviceKeyBundlePurpose,
} from "./types";


export default __t.row({
  id: __t.u64(),
  targetDeviceId: __t.string().name("target_device_id"),
  sourceDeviceId: __t.string().name("source_device_id"),
  accountId: __t.u64().name("account_id"),
  sourceEncryptionPublicKey: __t.string().name("source_encryption_public_key"),
  sourceEncryptionKeyVersion: __t.u32().name("source_encryption_key_version"),
  get sourceEncryptionAlgorithm() {
    return DeviceEncryptionAlgorithm.name("source_encryption_algorithm");
  },
  bundleCiphertext: __t.byteArray().name("bundle_ciphertext"),
  bundleIv: __t.byteArray().name("bundle_iv"),
  get bundleAlgorithm() {
    return DeviceBundleAlgorithm.name("bundle_algorithm");
  },
  get purpose() {
    return DeviceKeyBundlePurpose;
  },
  sharedAgentCount: __t.u64().name("shared_agent_count"),
  sharedKeyVersionCount: __t.u64().name("shared_key_version_count"),
  expiresAt: __t.timestamp().name("expires_at"),
  consumedAt: __t.option(__t.timestamp()).name("consumed_at"),
  pendingSortKey: __t.i64().name("pending_sort_key"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
