// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  deviceId: __t.string().name("device_id"),
  accountId: __t.u64().name("account_id"),
  verificationCodeHash: __t.string().name("verification_code_hash"),
  clientCreatedAt: __t.timestamp().name("client_created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  approvedAt: __t.option(__t.timestamp()).name("approved_at"),
  consumedAt: __t.option(__t.timestamp()).name("consumed_at"),
  pendingSortKey: __t.i64().name("pending_sort_key"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
