// This file is generated by scripts/prepare-spacetime-env.mjs.
// Re-run `pnpm run spacetime:prepare-env` after changing MASUMI_OIDC_ISSUER, MASUMI_OIDC_CLIENT_ID, MASUMI_OIDC_AUDIENCES, MASUMI_NETWORK, SPACETIMEDB_HOST, or SPACETIMEDB_DB_NAME.

pub const GENERATED_OIDC_CONFIG_SOURCE: &str = "explicit";
pub const GENERATED_MASUMI_OIDC_ISSUER: &str = "https://app.masumi.network";
pub const GENERATED_MASUMI_OIDC_CLIENT_ID: &str = "masumi-spacetime-web";
pub const GENERATED_MASUMI_OIDC_AUDIENCES: &[&str] = &[
  "masumi-spacetime-web",
  "masumi-spacetime-cli",
];
pub const TRUSTED_OIDC_ISSUERS: &[&str] = &[GENERATED_MASUMI_OIDC_ISSUER];
pub const TRUSTED_OIDC_AUDIENCES: &[&str] = GENERATED_MASUMI_OIDC_AUDIENCES;
pub const GENERATED_MASUMI_NETWORK: &str = "Mainnet";
pub const GENERATED_SPACETIMEDB_HOST: &str = "https://maincloud.spacetimedb.com";
pub const GENERATED_SPACETIMEDB_DB_NAME: &str = "masumi-agent-messenger-3rx0g";
