export const DEVICE_VERIFICATION_CODE_CONTEXT = 'masumi-device-share-code:v1';
export const DEVICE_VERIFICATION_CODE_ARGON2_ITERATIONS = 3;
export const DEVICE_VERIFICATION_CODE_ARGON2_MEMORY_KIB = 65_536;
export const DEVICE_VERIFICATION_CODE_ARGON2_PARALLELISM = 1;
export const DEVICE_SHARE_REQUEST_MAX_AGE_MS = 5 * 60_000;
export const DEVICE_SHARE_REQUEST_MAX_FUTURE_SKEW_MS = 5 * 60_000;
export const DEVICE_SHARE_REQUEST_EXPIRY_MS = 5 * 60_000;
