// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptThreadInviteReducer from "../accept_thread_invite_reducer";
import AddContactAllowlistEntryReducer from "../add_contact_allowlist_entry_reducer";
import AddThreadParticipantReducer from "../add_thread_participant_reducer";
import ApproveChannelJoinReducer from "../approve_channel_join_reducer";
import ApproveContactRequestReducer from "../approve_contact_request_reducer";
import ApproveDeviceShareReducer from "../approve_device_share_reducer";
import BackfillThreadSecretEnvelopesReducer from "../backfill_thread_secret_envelopes_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateDeviceShareRequestReducer from "../create_device_share_request_reducer";
import CreateDirectThreadReducer from "../create_direct_thread_reducer";
import CreateGroupThreadReducer from "../create_group_thread_reducer";
import CreateInboxIdentityReducer from "../create_inbox_identity_reducer";
import CreatePendingDirectContactRequestReducer from "../create_pending_direct_contact_request_reducer";
import DeleteThreadReducer from "../delete_thread_reducer";
import JoinPublicChannelReducer from "../join_public_channel_reducer";
import MarkThreadReadReducer from "../mark_thread_read_reducer";
import RefreshInboxAuthLeaseReducer from "../refresh_inbox_auth_lease_reducer";
import RegisterDeviceReducer from "../register_device_reducer";
import RejectChannelJoinReducer from "../reject_channel_join_reducer";
import RejectContactRequestReducer from "../reject_contact_request_reducer";
import RejectThreadInviteReducer from "../reject_thread_invite_reducer";
import RemoveChannelMemberReducer from "../remove_channel_member_reducer";
import RemoveContactAllowlistEntryReducer from "../remove_contact_allowlist_entry_reducer";
import RemoveThreadParticipantReducer from "../remove_thread_participant_reducer";
import RequestChannelJoinReducer from "../request_channel_join_reducer";
import RequestDirectContactWithFirstMessageReducer from "../request_direct_contact_with_first_message_reducer";
import RevokeDeviceReducer from "../revoke_device_reducer";
import RotateAgentKeysReducer from "../rotate_agent_keys_reducer";
import SendChannelMessageReducer from "../send_channel_message_reducer";
import SendEncryptedMessageReducer from "../send_encrypted_message_reducer";
import SetAgentPublicDescriptionReducer from "../set_agent_public_description_reducer";
import SetAgentPublicLinkedEmailVisibilityReducer from "../set_agent_public_linked_email_visibility_reducer";
import SetAgentPublicMessageCapabilitiesReducer from "../set_agent_public_message_capabilities_reducer";
import SetChannelMemberPermissionReducer from "../set_channel_member_permission_reducer";
import SetThreadArchivedReducer from "../set_thread_archived_reducer";
import SetThreadParticipantAdminReducer from "../set_thread_participant_admin_reducer";
import UpdateAgentProfileReducer from "../update_agent_profile_reducer";
import UpdateChannelSettingsReducer from "../update_channel_settings_reducer";
import UpsertInboxFromOidcIdentityReducer from "../upsert_inbox_from_oidc_identity_reducer";
import UpsertMasumiInboxAgentRegistrationReducer from "../upsert_masumi_inbox_agent_registration_reducer";

export type AcceptThreadInviteParams = __Infer<typeof AcceptThreadInviteReducer>;
export type AddContactAllowlistEntryParams = __Infer<typeof AddContactAllowlistEntryReducer>;
export type AddThreadParticipantParams = __Infer<typeof AddThreadParticipantReducer>;
export type ApproveChannelJoinParams = __Infer<typeof ApproveChannelJoinReducer>;
export type ApproveContactRequestParams = __Infer<typeof ApproveContactRequestReducer>;
export type ApproveDeviceShareParams = __Infer<typeof ApproveDeviceShareReducer>;
export type BackfillThreadSecretEnvelopesParams = __Infer<typeof BackfillThreadSecretEnvelopesReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateDeviceShareRequestParams = __Infer<typeof CreateDeviceShareRequestReducer>;
export type CreateDirectThreadParams = __Infer<typeof CreateDirectThreadReducer>;
export type CreateGroupThreadParams = __Infer<typeof CreateGroupThreadReducer>;
export type CreateInboxIdentityParams = __Infer<typeof CreateInboxIdentityReducer>;
export type CreatePendingDirectContactRequestParams = __Infer<typeof CreatePendingDirectContactRequestReducer>;
export type DeleteThreadParams = __Infer<typeof DeleteThreadReducer>;
export type JoinPublicChannelParams = __Infer<typeof JoinPublicChannelReducer>;
export type MarkThreadReadParams = __Infer<typeof MarkThreadReadReducer>;
export type RefreshInboxAuthLeaseParams = __Infer<typeof RefreshInboxAuthLeaseReducer>;
export type RegisterDeviceParams = __Infer<typeof RegisterDeviceReducer>;
export type RejectChannelJoinParams = __Infer<typeof RejectChannelJoinReducer>;
export type RejectContactRequestParams = __Infer<typeof RejectContactRequestReducer>;
export type RejectThreadInviteParams = __Infer<typeof RejectThreadInviteReducer>;
export type RemoveChannelMemberParams = __Infer<typeof RemoveChannelMemberReducer>;
export type RemoveContactAllowlistEntryParams = __Infer<typeof RemoveContactAllowlistEntryReducer>;
export type RemoveThreadParticipantParams = __Infer<typeof RemoveThreadParticipantReducer>;
export type RequestChannelJoinParams = __Infer<typeof RequestChannelJoinReducer>;
export type RequestDirectContactWithFirstMessageParams = __Infer<typeof RequestDirectContactWithFirstMessageReducer>;
export type RevokeDeviceParams = __Infer<typeof RevokeDeviceReducer>;
export type RotateAgentKeysParams = __Infer<typeof RotateAgentKeysReducer>;
export type SendChannelMessageParams = __Infer<typeof SendChannelMessageReducer>;
export type SendEncryptedMessageParams = __Infer<typeof SendEncryptedMessageReducer>;
export type SetAgentPublicDescriptionParams = __Infer<typeof SetAgentPublicDescriptionReducer>;
export type SetAgentPublicLinkedEmailVisibilityParams = __Infer<typeof SetAgentPublicLinkedEmailVisibilityReducer>;
export type SetAgentPublicMessageCapabilitiesParams = __Infer<typeof SetAgentPublicMessageCapabilitiesReducer>;
export type SetChannelMemberPermissionParams = __Infer<typeof SetChannelMemberPermissionReducer>;
export type SetThreadArchivedParams = __Infer<typeof SetThreadArchivedReducer>;
export type SetThreadParticipantAdminParams = __Infer<typeof SetThreadParticipantAdminReducer>;
export type UpdateAgentProfileParams = __Infer<typeof UpdateAgentProfileReducer>;
export type UpdateChannelSettingsParams = __Infer<typeof UpdateChannelSettingsReducer>;
export type UpsertInboxFromOidcIdentityParams = __Infer<typeof UpsertInboxFromOidcIdentityReducer>;
export type UpsertMasumiInboxAgentRegistrationParams = __Infer<typeof UpsertMasumiInboxAgentRegistrationReducer>;

