// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptThreadInviteReducer from "../accept_thread_invite_reducer";
import AddContactAllowlistEntryReducer from "../add_contact_allowlist_entry_reducer";
import AddThreadParticipantReducer from "../add_thread_participant_reducer";
import ApproveChannelJoinReducer from "../approve_channel_join_reducer";
import ApproveContactRequestReducer from "../approve_contact_request_reducer";
import ApproveDeviceShareRequestReducer from "../approve_device_share_request_reducer";
import CancelContactRequestReducer from "../cancel_contact_request_reducer";
import CreateAgentReducer from "../create_agent_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateDeviceShareRequestReducer from "../create_device_share_request_reducer";
import CreateThreadReducer from "../create_thread_reducer";
import DeclineThreadInviteReducer from "../decline_thread_invite_reducer";
import DeleteThreadReducer from "../delete_thread_reducer";
import JoinPublicChannelReducer from "../join_public_channel_reducer";
import RefreshAccountAuthLeaseReducer from "../refresh_account_auth_lease_reducer";
import RegisterDeviceReducer from "../register_device_reducer";
import RejectChannelJoinReducer from "../reject_channel_join_reducer";
import RejectContactRequestReducer from "../reject_contact_request_reducer";
import RemoveChannelMemberReducer from "../remove_channel_member_reducer";
import RemoveContactAllowlistEntryReducer from "../remove_contact_allowlist_entry_reducer";
import RemoveThreadParticipantReducer from "../remove_thread_participant_reducer";
import RequestChannelJoinReducer from "../request_channel_join_reducer";
import RequestDirectContactReducer from "../request_direct_contact_reducer";
import RevokeDeviceReducer from "../revoke_device_reducer";
import RotateAgentKeysReducer from "../rotate_agent_keys_reducer";
import SendChannelMessageReducer from "../send_channel_message_reducer";
import SendEncryptedMessageReducer from "../send_encrypted_message_reducer";
import SetThreadParticipantAdminReducer from "../set_thread_participant_admin_reducer";
import ShareDeviceKeyBundleReducer from "../share_device_key_bundle_reducer";
import UpdateAgentProfileReducer from "../update_agent_profile_reducer";
import UpdateChannelMemberPermissionReducer from "../update_channel_member_permission_reducer";
import UpdateChannelMemberReadStateReducer from "../update_channel_member_read_state_reducer";
import UpdateChannelSettingsReducer from "../update_channel_settings_reducer";
import UpdateThreadMessageRetentionReducer from "../update_thread_message_retention_reducer";
import UpdateThreadReadStateReducer from "../update_thread_read_state_reducer";
import UpsertAccountFromOidcIdentityReducer from "../upsert_account_from_oidc_identity_reducer";
import UpsertMasumiRegistrationReducer from "../upsert_masumi_registration_reducer";

export type AcceptThreadInviteParams = __Infer<typeof AcceptThreadInviteReducer>;
export type AddContactAllowlistEntryParams = __Infer<typeof AddContactAllowlistEntryReducer>;
export type AddThreadParticipantParams = __Infer<typeof AddThreadParticipantReducer>;
export type ApproveChannelJoinParams = __Infer<typeof ApproveChannelJoinReducer>;
export type ApproveContactRequestParams = __Infer<typeof ApproveContactRequestReducer>;
export type ApproveDeviceShareRequestParams = __Infer<typeof ApproveDeviceShareRequestReducer>;
export type CancelContactRequestParams = __Infer<typeof CancelContactRequestReducer>;
export type CreateAgentParams = __Infer<typeof CreateAgentReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateDeviceShareRequestParams = __Infer<typeof CreateDeviceShareRequestReducer>;
export type CreateThreadParams = __Infer<typeof CreateThreadReducer>;
export type DeclineThreadInviteParams = __Infer<typeof DeclineThreadInviteReducer>;
export type DeleteThreadParams = __Infer<typeof DeleteThreadReducer>;
export type JoinPublicChannelParams = __Infer<typeof JoinPublicChannelReducer>;
export type RefreshAccountAuthLeaseParams = __Infer<typeof RefreshAccountAuthLeaseReducer>;
export type RegisterDeviceParams = __Infer<typeof RegisterDeviceReducer>;
export type RejectChannelJoinParams = __Infer<typeof RejectChannelJoinReducer>;
export type RejectContactRequestParams = __Infer<typeof RejectContactRequestReducer>;
export type RemoveChannelMemberParams = __Infer<typeof RemoveChannelMemberReducer>;
export type RemoveContactAllowlistEntryParams = __Infer<typeof RemoveContactAllowlistEntryReducer>;
export type RemoveThreadParticipantParams = __Infer<typeof RemoveThreadParticipantReducer>;
export type RequestChannelJoinParams = __Infer<typeof RequestChannelJoinReducer>;
export type RequestDirectContactParams = __Infer<typeof RequestDirectContactReducer>;
export type RevokeDeviceParams = __Infer<typeof RevokeDeviceReducer>;
export type RotateAgentKeysParams = __Infer<typeof RotateAgentKeysReducer>;
export type SendChannelMessageParams = __Infer<typeof SendChannelMessageReducer>;
export type SendEncryptedMessageParams = __Infer<typeof SendEncryptedMessageReducer>;
export type SetThreadParticipantAdminParams = __Infer<typeof SetThreadParticipantAdminReducer>;
export type ShareDeviceKeyBundleParams = __Infer<typeof ShareDeviceKeyBundleReducer>;
export type UpdateAgentProfileParams = __Infer<typeof UpdateAgentProfileReducer>;
export type UpdateChannelMemberPermissionParams = __Infer<typeof UpdateChannelMemberPermissionReducer>;
export type UpdateChannelMemberReadStateParams = __Infer<typeof UpdateChannelMemberReadStateReducer>;
export type UpdateChannelSettingsParams = __Infer<typeof UpdateChannelSettingsReducer>;
export type UpdateThreadMessageRetentionParams = __Infer<typeof UpdateThreadMessageRetentionReducer>;
export type UpdateThreadReadStateParams = __Infer<typeof UpdateThreadReadStateReducer>;
export type UpsertAccountFromOidcIdentityParams = __Infer<typeof UpsertAccountFromOidcIdentityReducer>;
export type UpsertMasumiRegistrationParams = __Infer<typeof UpsertMasumiRegistrationReducer>;

